import {applyColorRules} from './art-color-core.js?v=2.17.3';
import {openGarmentComposer} from './garment-composer.js?v=2.17.3';
import {createGarmentCloudStore} from './garment-cloud-store.js?v=2.17.3';

const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=value=>Number(String(value??'').trim().replace(',','.'));
const decimal=value=>Number(value).toLocaleString('pt-BR',{maximumFractionDigits:2});
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const frame=()=>new Promise(resolve=>requestAnimationFrame(resolve));
const toBlob=canvas=>new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('O navegador não conseguiu gerar o PNG.')),'image/png'));

export function shirtScale(stageWidth,shirtWidthCm){return stageWidth*.59/shirtWidthCm}
export function shirtStageRatio(widthCm,lengthCm){return (lengthCm/widthCm)*(.59/.89)}

function mountDialog(title,subtitle,content,footer,variant){
  const previous=document.activeElement,modal=document.createElement('div');modal.className='art-studio-backdrop';
  modal.innerHTML=`<section class="art-studio ${variant}" role="dialog" aria-modal="true" aria-label="${escape(title)}"><header class="art-studio-head"><div><span class="studio-eyebrow">ZERO 19 / ESTÚDIO</span><h2>${escape(title)}</h2><p>${escape(subtitle)}</p></div><button class="studio-close" aria-label="Fechar">×</button></header>${content}<footer class="art-studio-footer">${footer}</footer><div class="studio-message" aria-live="polite"></div></section>`;
  document.body.append(modal);const oldOverflow=document.body.style.overflow,controller=new AbortController();document.body.style.overflow='hidden';let busy=false,closed=false,cleanup=()=>{};
  const close=(force=false)=>{if(closed||busy&&!force)return;closed=true;window.removeEventListener('z19:account-changing',accountChanging);controller.abort();cleanup();modal.remove();document.body.style.overflow=force?'':oldOverflow;if(!force&&previous?.isConnected)previous.focus()};
  const accountChanging=()=>close(true);window.addEventListener('z19:account-changing',accountChanging);
  modal.querySelector('.studio-close').onclick=()=>close();
  modal.addEventListener('keydown',event=>{if(event.key==='Escape'){event.stopPropagation();close()}if(event.key==='Tab'){const controls=[...modal.querySelectorAll('button,input,select,[tabindex="0"]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}});
  modal.querySelector('.studio-close').focus();
  return {modal,close,signal:controller.signal,isClosed:()=>closed,query:selector=>modal.querySelector(selector),setBusy:value=>{if(closed)return;busy=value;modal.querySelector('.studio-close').disabled=value},onCleanup:fn=>{cleanup=fn;if(closed)cleanup()},message:(text,error=false)=>{if(closed)return;const box=modal.querySelector('.studio-message');box.textContent=text;box.classList.toggle('error',error)}};
}

async function loadImage(url){const image=new Image();image.crossOrigin='anonymous';image.src=url;try{await image.decode()}catch{throw new Error('Não foi possível abrir esta arte. Confira a conexão e tente novamente.')}return image}

export function createArtStudio(ctx){
  const {supabase}=ctx,owner=()=>ctx.accountOwnerId(),user=()=>ctx.state().session?.user?.id;
  const assertActive=signal=>{if(signal?.aborted)throw new DOMException('Operação interrompida ao fechar o estúdio ou trocar a conta.','AbortError')};
  const getProfile=async asset=>{const {data,error}=await supabase.from('z19p_asset_print_profiles').select('*').eq('asset_id',asset.id).maybeSingle();if(error)throw error;return data};
  const assetUrl=asset=>ctx.publicUrl(asset.processed_path||asset.original_path);

  async function openMockup(asset,options={}){
    if(!asset||asset.asset_type!=='arte')return;
    const dialog=mountDialog('Veja sua arte na peça',asset.name,`<div class="studio-loading">Preparando o provador…</div>`,'<span>Escala física ajustável • frente, costas e mangas</span>','shirt-studio');
    try{
      const [profile,image]=await Promise.all([getProfile(asset),loadImage(assetUrl(asset))]);if(!dialog.modal.isConnected)return;
      const ratio=image.naturalWidth/image.naturalHeight,placement=asset.metadata?.shirt_placement||{},state={side:placement.side||'front',color:placement.color||'black',shirtWidth:placement.shirt_width_cm||54,shirtLength:placement.shirt_length_cm||74,sleeveWidth:placement.sleeve_width_cm||18,sleeveLength:placement.sleeve_length_cm||22,width:Number(profile?.default_width_cm)||Math.min(28,image.naturalWidth/300*2.54),x:placement.x_cm??27,y:placement.y_cm??25};
      if(!profile)state.width=Math.max(1,state.width);let zoom=1,drag=null,observer;const positions={...(placement.positions||{})};const isSleeve=()=>state.side==='left'||state.side==='right';const surface=()=>isSleeve()?{width:state.sleeveWidth,length:state.sleeveLength,fraction:.23,heightFraction:.32,left:state.side==='left'?.435:.335,top:.15}:{width:state.shirtWidth,length:state.shirtLength,fraction:.59,heightFraction:.89,left:.205,top:.05};
      if(isSleeve()&&!positions[state.side]){state.x=state.sleeveWidth/2;state.y=state.sleeveLength/2}
      dialog.query('.studio-loading').outerHTML=`<div class="shirt-studio-layout"><div class="shirt-visual"><div class="shirt-top-controls"><div class="studio-segment" aria-label="Lado da camisa"><button data-side="front" class="active">Frente</button><button data-side="back">Costas</button><button data-side="left">Manga esq.</button><button data-side="right">Manga dir.</button></div><div class="shirt-colors" aria-label="Cor da camisa"><button class="black active" data-color="black" aria-label="Camisa preta"></button><button class="white" data-color="white" aria-label="Camisa branca"></button></div></div><div class="shirt-stage-viewport"><div class="shirt-stage"><div class="shirt-surface"></div><div class="shirt-body-guide"></div><div class="shirt-art" tabindex="0" role="group" aria-label="Arte na camisa; use as setas para mover"><img src="${escape(assetUrl(asset))}" alt="${escape(asset.name)}" draggable="false"><span class="shirt-art-size"></span><button class="shirt-resize" aria-label="Arraste para alterar o tamanho">↘</button></div><div class="shirt-width-ruler"></div></div></div><div class="shirt-visual-help"><span>Arraste a arte • use o canto discreto para redimensionar</span><label>Zoom <input class="shirt-zoom" type="range" min="100" max="180" value="100" aria-label="Zoom do provador"></label></div></div><aside class="shirt-settings"><span class="studio-eyebrow">TAMANHO DA ESTAMPA</span><div class="shirt-dimensions"><label>Largura <span>cm</span><input id="shirtArtWidth" inputmode="decimal"></label><span>×</span><label>Altura <span>cm</span><input id="shirtArtHeight" inputmode="decimal"></label></div><p class="studio-note">Proporção original preservada ao editar qualquer medida.</p><div class="shirt-presets"><button data-size="9">Peito · 9 cm</button><button data-size="20">Média · 20 cm</button><button data-size="28">Grande · 28 cm</button><button data-size="43" data-back-only hidden>Costas · 43 cm</button></div><button class="studio-secondary" id="centerShirtArt">Centralizar arte</button><div class="studio-divider"></div><span class="studio-eyebrow">MEDIDA REAL DA CAMISETA</span><div class="shirt-measure-fields"><label><span id="shirtMeasureWidthLabel">Largura do corpo (cm)</span><input id="shirtBodyWidth" inputmode="decimal" value="${decimal(state.shirtWidth)}"></label><label><span id="shirtMeasureLengthLabel">Ombro até a barra (cm)</span><input id="shirtBodyLength" inputmode="decimal" value="${decimal(state.shirtLength)}"></label></div><p class="studio-note" id="shirtMeasureNote">Meça a peça estendida, de uma lateral à outra. A simulação usa estas medidas; o caimento no corpo varia.</p><div class="shirt-scale-status"></div><label class="studio-check"><input id="shirtHalftone" type="checkbox" ${profile?.halftone?'checked':''}>Esta arte é halftone</label><label class="studio-check"><input id="shirtReady" type="checkbox" ${profile?.ready_for_print?'checked':''}>Liberar esta arte no Montar Filme</label></aside></div>`;
      dialog.query('.art-studio-footer').innerHTML=`<div><b class="shirt-footer-size"></b><small>${profile?'A medida cadastrada só muda ao salvar.':'Defina a medida e escolha se deseja liberar para impressão.'}</small></div><button class="studio-primary" id="saveShirtSize">Salvar tamanho da arte</button>`;
      if(ctx.isGarmentStudioEnabled?.()){
        dialog.query('.shirt-settings').insertAdjacentHTML('afterbegin','<button class="studio-primary open-complete-garment">Montar camiseta completa ↗</button><p class="studio-note">Várias estampas, normal ou oversized, off-white e apresentação para o cliente.</p><div class="studio-divider"></div>');
        dialog.query('.open-complete-garment').onclick=()=>{dialog.close();openGarmentComposer(ctx,asset,{...options,width:state.width,side:state.side,placement:{...state}})};
      }
      const stage=dialog.query('.shirt-stage'),art=dialog.query('.shirt-art'),widthInput=dialog.query('#shirtArtWidth'),heightInput=dialog.query('#shirtArtHeight');
      const update=(syncInputs=true)=>{
        const face=surface();stage.style.aspectRatio=`1 / ${(face.length/face.width)*(face.fraction/face.heightFraction)}`;stage.style.width=`${zoom*100}%`;stage.style.maxWidth='none';
        const size=stage.clientWidth,scale=size*face.fraction/face.width,height=state.width/ratio,left=face.left*size,top=face.top*stage.clientHeight;
        art.style.width=`${state.width*scale}px`;art.style.height=`${height*scale}px`;art.style.left=`${left+state.x*scale}px`;art.style.top=`${top+state.y*scale}px`;
        const backdrop=dialog.query('.shirt-surface');backdrop.style.backgroundImage=`url('./assets/${isSleeve()?'shirt-sleeves-atlas.png':'shirt-studio-atlas.png'}')`;backdrop.style.backgroundPosition=`${state.side==='front'||state.side==='left'?'0':'100'}% ${state.color==='black'?'0':'100'}%`;
        dialog.modal.querySelectorAll('[data-side]').forEach(b=>b.classList.toggle('active',b.dataset.side===state.side));dialog.modal.querySelectorAll('[data-color]').forEach(b=>b.classList.toggle('active',b.dataset.color===state.color));const backOnly=dialog.query('[data-back-only]');if(backOnly)backOnly.hidden=state.side!=='back';
        if(syncInputs){widthInput.value=decimal(state.width);heightInput.value=decimal(height)}
        const dimensions=`${decimal(state.width)} × ${decimal(height)} cm`;dialog.query('.shirt-art-size').textContent=dimensions;dialog.query('.shirt-footer-size').textContent=dimensions;
        dialog.query('.shirt-width-ruler').textContent=`← ${isSleeve()?'face externa da manga':'corpo da camiseta'}: ${decimal(face.width)} cm →`;
        const outside=state.x-state.width/2<0||state.x+state.width/2>face.width||state.y-height/2<0||state.y+height/2>face.length;
        dialog.query('.shirt-scale-status').textContent=outside?'Parte da arte está fora da superfície medida. Ajuste a posição ou o tamanho.':`Escala: arte de ${decimal(state.width)} cm em uma peça de ${decimal(face.width)} cm.`;dialog.query('.shirt-scale-status').classList.toggle('warning',outside);
      };
      widthInput.oninput=()=>{const value=number(widthInput.value);if(value>0&&value<=200){state.width=value;heightInput.value=decimal(value/ratio);update(false)}};
      heightInput.oninput=()=>{const value=number(heightInput.value);if(value>0&&value*ratio<=200){state.width=value*ratio;widthInput.value=decimal(state.width);update(false)}};
      dialog.modal.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{state.width=Number(b.dataset.size);update()});
      const syncMeasurements=()=>{const face=surface();dialog.query('#shirtBodyWidth').value=decimal(face.width);dialog.query('#shirtBodyLength').value=decimal(face.length);dialog.query('#shirtMeasureWidthLabel').textContent=isSleeve()?'Largura externa da manga (cm)':'Largura do corpo (cm)';dialog.query('#shirtMeasureLengthLabel').textContent=isSleeve()?'Costura até a barra (cm)':'Ombro até a barra (cm)';dialog.query('#shirtMeasureNote').textContent=isSleeve()?'Esquerda/direita de quem veste. Meça a face externa da manga estendida; a curvatura real pode mudar a aparência.':'Meça a peça estendida, de uma lateral à outra. A simulação usa estas medidas; o caimento no corpo varia.'};
      dialog.modal.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{positions[state.side]={x:state.x,y:state.y};state.side=b.dataset.side;const face=surface(),position=positions[state.side];state.x=position?.x??face.width/2;state.y=position?.y??face.length*(isSleeve()?.5:.36);syncMeasurements();stage.classList.remove('flipping');void stage.offsetWidth;stage.classList.add('flipping');update()});
      dialog.modal.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{state.color=b.dataset.color;update()});
      for(const [id,bodyKey,sleeveKey,min,max] of [['#shirtBodyWidth','shirtWidth','sleeveWidth',20,120],['#shirtBodyLength','shirtLength','sleeveLength',25,150]])dialog.query(id).oninput=e=>{const value=number(e.target.value);if(value>=(isSleeve()?5:min)&&value<=(isSleeve()?60:max)){state[isSleeve()?sleeveKey:bodyKey]=value;update()}};
      dialog.query('#centerShirtArt').onclick=()=>{const face=surface();state.x=face.width/2;state.y=face.length*(isSleeve()?.5:.36);update()};
      dialog.query('.shirt-zoom').oninput=e=>{zoom=number(e.target.value)/100;update()};
      art.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();art.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY,artX:state.x,artY:state.y,width:state.width,resize:Boolean(e.target.closest('.shirt-resize'))}};
      art.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const face=surface(),scale=stage.clientWidth*face.fraction/face.width,dx=(e.clientX-drag.x)/scale,dy=(e.clientY-drag.y)/scale;if(drag.resize)state.width=clamp(drag.width+dx*2,1,150);else{state.x=clamp(drag.artX+dx,-face.width*.2,face.width*1.2);state.y=clamp(drag.artY+dy,0,face.length)}update()};
      art.onpointerup=art.onpointercancel=()=>{drag=null};
      art.onkeydown=e=>{const movements={ArrowLeft:[-.5,0],ArrowRight:[.5,0],ArrowUp:[0,-.5],ArrowDown:[0,.5]};if(movements[e.key]){e.preventDefault();state.x+=movements[e.key][0];state.y+=movements[e.key][1];update()}};
      observer=new ResizeObserver(()=>update(false));observer.observe(stage);dialog.onCleanup(()=>observer.disconnect());syncMeasurements();update();
      dialog.query('#saveShirtSize').onclick=async()=>{
        const width=number(widthInput.value),height=width/ratio,bodyWidth=number(dialog.query('#shirtBodyWidth').value),bodyLength=number(dialog.query('#shirtBodyLength').value);
        if(!(width>0&&width<=200&&number(heightInput.value)>0&&bodyWidth>=(isSleeve()?5:20)&&bodyWidth<=(isSleeve()?60:120)&&bodyLength>=(isSleeve()?5:25)&&bodyLength<=(isSleeve()?60:150)))return dialog.message('Preencha medidas válidas para a arte e a camiseta.',true);
        dialog.setBusy(true);const button=dialog.query('#saveShirtSize');button.disabled=true;button.textContent='Salvando…';
        try{
          const halftone=dialog.query('#shirtHalftone').checked,ready=dialog.query('#shirtReady').checked,payload={asset_id:asset.id,owner_id:owner(),project_id:asset.project_id||null,default_width_cm:width,default_height_cm:height,aspect_ratio:ratio,halftone,allow_internal_nesting:halftone?false:(profile?.allow_internal_nesting!==false),rotation_policy:profile?.rotation_policy||'180',ready_for_print:ready,created_by:profile?.created_by||user(),updated_by:user(),updated_at:new Date().toISOString()};
          assertActive(dialog.signal);const result=await supabase.from('z19p_asset_print_profiles').upsert(payload,{onConflict:'asset_id'});assertActive(dialog.signal);if(result.error)throw result.error;
          const metadata={...(asset.metadata||{}),shirt_placement:{side:state.side,color:state.color,x_cm:state.x,y_cm:state.y,shirt_width_cm:state.shirtWidth,shirt_length_cm:state.shirtLength,sleeve_width_cm:state.sleeveWidth,sleeve_length_cm:state.sleeveLength,positions:{...positions,[state.side]:{x:state.x,y:state.y}}}};
          const saved=await supabase.from('z19p_assets').update({metadata,updated_by:user(),updated_at:new Date().toISOString()}).eq('id',asset.id);assertActive(dialog.signal);if(saved.error)throw saved.error;asset.metadata=metadata;
          await ctx.logEvent('asset_print_profile_updated',`Ajustou ${decimal(width)} × ${decimal(height)} cm no provador`,{workspaceId:asset.workspace_id,projectId:asset.project_id,entityType:'asset',entityId:asset.id,metadata:{width_cm:width,height_cm:height,halftone}});
          assertActive(dialog.signal);dialog.setBusy(false);dialog.close();ctx.toast('Medida e posição salvas.','ok');options.onSaved?.(payload);await ctx.onAssetChanged?.(asset);
        }catch(error){dialog.message(error.message||'Não foi possível salvar a medida.',true)}finally{dialog.setBusy(false);button.disabled=false;button.textContent='Salvar tamanho da arte'}
      };
    }catch(error){dialog.message(error.message,true);dialog.query('.studio-loading')?.remove()}
    return dialog;
  }

  async function openEditor(asset,options={}){
    if(!asset||asset.asset_type!=='arte')return;
    const dialog=mountDialog('Editar arte',asset.name,'<div class="studio-loading">Abrindo a arte em alta resolução…</div>','<span>O original é preservado em cada revisão.</span>','color-studio');
    try{
      const [image,profile]=await Promise.all([loadImage(assetUrl(asset)),getProfile(asset)]);if(!dialog.modal.isConnected)return;
      const preview=document.createElement('canvas'),scale=Math.min(1,1400/Math.max(image.naturalWidth,image.naturalHeight));preview.width=Math.round(image.naturalWidth*scale);preview.height=Math.round(image.naturalHeight*scale);const pg=preview.getContext('2d',{willReadFrequently:true});pg.drawImage(image,0,0,preview.width,preview.height);const original=pg.getImageData(0,0,preview.width,preview.height);let rules=[],redo=[],selected=null,tolerance=18,feather=4,showSelection=true,zoom=1,worker=null,closed=false;
      dialog.query('.studio-loading').outerHTML=`<div class="color-studio-layout"><div class="color-workspace"><div class="color-toolbar"><button class="studio-tool active" id="colorEyedropper" title="Conta-gotas (W)">⌖ Conta-gotas</button><button class="studio-tool" id="undoColor" disabled>↶ Desfazer</button><button class="studio-tool" id="redoColor" disabled>↷ Refazer</button><select id="editorBackground" aria-label="Fundo de visualização"><option value="check">Transparente</option><option value="black">Camisa preta</option><option value="white">Camisa branca</option></select></div><div class="color-canvas-scroll check"><div class="color-canvas-wrap"></div></div><div class="color-canvas-info"><span>${image.naturalWidth} × ${image.naturalHeight} px • PNG 300 DPI</span><label>Zoom <input id="editorZoom" type="range" min="100" max="300" value="100" aria-label="Zoom da arte"></label></div></div><aside class="color-settings"><span class="studio-eyebrow">REMOVER UMA COR</span><h3>Toque na cor da arte</h3><p class="studio-note">O conta-gotas seleciona essa cor em toda a imagem, inclusive nas áreas separadas.</p><div class="color-sample"><span></span><div><b>Nenhuma cor escolhida</b><small>Toque na imagem para selecionar</small></div></div><label class="studio-slider">Tolerância <output id="toleranceValue">18</output><input id="colorTolerance" type="range" min="0" max="120" value="18"></label><p class="studio-note">Aumente para incluir tons parecidos. A seleção aparece em rosa antes de apagar.</p><label class="studio-slider">Suavizar borda <output id="featherValue">4</output><input id="colorFeather" type="range" min="0" max="24" value="4"></label><label class="studio-check"><input id="showColorSelection" type="checkbox" checked>Mostrar seleção</label><button class="studio-primary" id="eraseColor" disabled>Apagar cor selecionada</button><button class="studio-secondary" id="clearColorSelection">Limpar seleção</button><div class="studio-divider"></div><label class="studio-field">Nome da arte<input id="editedArtName" value="${escape(asset.name)}"></label><p class="studio-note">Apagar cria transparência. O fundo preto/branco é só para visualizar; ele não entra no arquivo.</p><div class="color-edits-status">Nenhuma alteração aplicada</div></aside></div>`;
      const canvas=document.createElement('canvas');canvas.width=preview.width;canvas.height=preview.height;canvas.setAttribute('aria-label','Arte: toque para selecionar uma cor');canvas.setAttribute('tabindex','0');dialog.query('.color-canvas-wrap').append(canvas);const g=canvas.getContext('2d',{willReadFrequently:true});
      dialog.query('.art-studio-footer').innerHTML='<span class="color-save-note">Salve uma cópia ou atualize a arte atual.</span><div><button class="studio-secondary" id="saveArtCopy" disabled>Salvar como nova arte</button><button class="studio-primary" id="saveArtUpdate" disabled>Atualizar esta arte</button></div>';
      const render=()=>{const data=new ImageData(new Uint8ClampedArray(original.data),original.width,original.height),stats=applyColorRules(data.data,rules,selected&&showSelection?{color:selected,tolerance}:null);g.putImageData(data,0,0);dialog.query('#eraseColor').disabled=!selected;dialog.query('#undoColor').disabled=!rules.length;dialog.query('#redoColor').disabled=!redo.length;dialog.query('#saveArtCopy').disabled=dialog.query('#saveArtUpdate').disabled=!rules.length;dialog.query('.color-edits-status').textContent=`${rules.length} cor(es) removida(s)${selected&&showSelection?` • ${stats.selected.toLocaleString('pt-BR')} pixels selecionados na prévia`:''}`;if(selected){const hex='#'+selected.map(n=>n.toString(16).padStart(2,'0')).join('');dialog.query('.color-sample>span').style.background=hex;dialog.query('.color-sample b').textContent=hex.toUpperCase();dialog.query('.color-sample small').textContent=`RGB ${selected.join(', ')}`}else{dialog.query('.color-sample b').textContent='Nenhuma cor escolhida';dialog.query('.color-sample small').textContent='Toque na imagem para selecionar'}};
      canvas.onclick=e=>{const rect=canvas.getBoundingClientRect(),x=clamp(Math.floor((e.clientX-rect.left)/rect.width*original.width),0,original.width-1),y=clamp(Math.floor((e.clientY-rect.top)/rect.height*original.height),0,original.height-1),index=(y*original.width+x)*4,pixel=new Uint8ClampedArray(original.data.slice(index,index+4));applyColorRules(pixel,rules);if(!pixel[3])return dialog.message('Essa área já é transparente. Escolha um pixel visível.');selected=[pixel[0],pixel[1],pixel[2]];dialog.message('Cor selecionada. Confira a área rosa antes de apagar.');render()};
      dialog.query('#eraseColor').onclick=()=>{if(!selected)return;rules.push({color:[...selected],tolerance,feather});redo=[];selected=null;render()};
      dialog.query('#undoColor').onclick=()=>{if(rules.length)redo.push(rules.pop());render()};dialog.query('#redoColor').onclick=()=>{if(redo.length)rules.push(redo.pop());render()};
      dialog.query('#clearColorSelection').onclick=()=>{selected=null;render()};dialog.query('#colorEyedropper').onclick=()=>canvas.focus();
      dialog.query('#colorTolerance').oninput=e=>{tolerance=Number(e.target.value);dialog.query('#toleranceValue').value=tolerance;render()};dialog.query('#colorFeather').oninput=e=>{feather=Number(e.target.value);dialog.query('#featherValue').value=feather};dialog.query('#showColorSelection').onchange=e=>{showSelection=e.target.checked;render()};
      dialog.query('#editorBackground').onchange=e=>{dialog.query('.color-canvas-scroll').className=`color-canvas-scroll ${e.target.value}`};
      dialog.query('#editorZoom').oninput=e=>{zoom=Number(e.target.value)/100;dialog.query('.color-canvas-wrap').style.width=`${zoom*100}%`};
      dialog.modal.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key.toLowerCase()==='w'){e.preventDefault();canvas.focus();dialog.message('Conta-gotas ativo. Toque na cor que deseja remover.')}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();dialog.query('#eraseColor').click()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();dialog.query(e.shiftKey?'#redoColor':'#undoColor').click()}});
      dialog.onCleanup(()=>{closed=true;worker?.terminate();preview.width=preview.height=canvas.width=canvas.height=1});render();
      const save=async duplicate=>{
        if(!rules.length)return;const name=dialog.query('#editedArtName').value.trim();if(!name)return dialog.message('Informe o nome da arte.',true);
        const saveButtons=[dialog.query('#saveArtCopy'),dialog.query('#saveArtUpdate')];dialog.setBusy(true);dialog.modal.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);dialog.message('Preparando PNG em resolução original…');let out=null;
        try{
          if(image.naturalWidth*image.naturalHeight>68e6)throw new Error('Esta imagem excede o limite de edição de 68 megapixels do navegador. Use uma cópia menor para editar.');
          out=document.createElement('canvas');out.width=image.naturalWidth;out.height=image.naturalHeight;const og=out.getContext('2d',{willReadFrequently:true});if(!og)throw new Error('Memória insuficiente para editar esta imagem.');og.drawImage(image,0,0);
          if(window.Worker)worker=new Worker(new URL('./art-color-worker.js?v=2.17.3',import.meta.url),{type:'module'});
          const stripHeight=Math.min(128,out.height);let remaining=0;
          for(let y=0;y<out.height;y+=stripHeight){assertActive(dialog.signal);const height=Math.min(stripHeight,out.height-y),strip=og.getImageData(0,y,out.width,height);if(worker){const result=await new Promise((resolve,reject)=>{let settled=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timeout);dialog.signal.removeEventListener('abort',abort);error?reject(error):resolve(value)},abort=()=>finish(new DOMException('Edição interrompida.','AbortError')),timeout=setTimeout(()=>finish(new Error('Tempo excedido ao processar a imagem.')),30000);dialog.signal.addEventListener('abort',abort,{once:true});worker.onmessage=e=>finish(e.data.error?new Error(e.data.error):null,e.data);worker.onerror=e=>finish(new Error(e.message));if(dialog.signal.aborted)return abort();worker.postMessage({buffer:strip.data.buffer,rules},[strip.data.buffer])});assertActive(dialog.signal);remaining+=result.remaining;og.putImageData(new ImageData(new Uint8ClampedArray(result.buffer),out.width,height),0,y)}else{remaining+=applyColorRules(strip.data,rules).remaining;og.putImageData(strip,0,y)}dialog.message(`Aplicando remoção em alta resolução… ${Math.round((y+height)/out.height*100)}%`);await frame()}
          if(!remaining)throw new Error('A edição apagou toda a arte. Desfaça a remoção ou diminua a tolerância.');
          assertActive(dialog.signal);let blob=await toBlob(out);assertActive(dialog.signal);blob=await ctx.setPngDpi(blob,300);assertActive(dialog.signal);const result=await persistEdit(asset,profile,blob,{duplicate,name,rules,width:out.width,height:out.height,signal:dialog.signal});assertActive(dialog.signal);
          dialog.setBusy(false);dialog.close();ctx.toast(duplicate?'Nova arte salva com transparência.':'Arte atualizada; original preservado.','ok');options.onSaved?.(result);await ctx.onAssetChanged?.(result);
        }catch(error){dialog.message(error.message||'Não foi possível salvar a edição.',true)}finally{worker?.terminate();worker=null;if(out)out.width=out.height=1;if(!closed){dialog.setBusy(false);dialog.modal.querySelectorAll('input,select,button').forEach(el=>el.disabled=false);render();saveButtons.forEach(button=>button.disabled=!rules.length)}}
      };
      dialog.query('#saveArtCopy').onclick=()=>save(true);dialog.query('#saveArtUpdate').onclick=()=>save(false);
    }catch(error){dialog.message(error.message,true);dialog.query('.studio-loading')?.remove()}
    return dialog;
  }

  async function persistEdit(asset,profile,blob,{duplicate,name,rules,width,height,signal}){
    assertActive(signal);
    const id=duplicate?crypto.randomUUID():asset.id,revision=crypto.randomUUID(),path=`${owner()}/${asset.workspace_id}/${id}/edits/${revision}.png`,now=new Date().toISOString();
    const upload=await supabase.storage.from('z19p-assets').upload(path,blob,{contentType:'image/png',upsert:false});assertActive(signal);if(upload.error)throw upload.error;
    const metadata={...(asset.metadata||{}),manual_color_edit:{rules,edited_at:now,edited_by:user(),previous_path:asset.processed_path||asset.original_path,source_asset_id:asset.id},revision_paths:[...new Set([...(asset.metadata?.revision_paths||[]),asset.processed_path||asset.original_path].filter(Boolean))]};
    let response;
    if(duplicate){const row={id,owner_id:owner(),workspace_id:asset.workspace_id,project_id:asset.project_id||null,folder_id:asset.folder_id||null,name:name===asset.name?`${name} — editada`:name,asset_type:'arte',original_path:path,processed_path:path,mime_type:'image/png',size_bytes:blob.size,width,height,dpi:300,alpha_trimmed:asset.alpha_trimmed||false,background_removed:false,maximized:asset.maximized||false,metadata,created_by:user(),updated_by:user()};response=await supabase.from('z19p_assets').insert(row).select().single()}
    else{let query=supabase.from('z19p_assets').update({name,processed_path:path,mime_type:'image/png',size_bytes:blob.size,width,height,dpi:300,metadata,updated_by:user(),updated_at:now}).eq('id',id);if(asset.updated_at)query=query.eq('updated_at',asset.updated_at);response=await query.select().single()}
    assertActive(signal);if(response.error){await supabase.storage.from('z19p-assets').remove([path]);throw new Error(response.error.code==='PGRST116'?'Esta arte mudou em outra tela. Reabra o editor para salvar a versão mais recente.':response.error.message)}
    if(duplicate&&profile){const {error}=await supabase.from('z19p_asset_print_profiles').insert({asset_id:id,owner_id:owner(),project_id:asset.project_id||null,default_width_cm:profile.default_width_cm,default_height_cm:profile.default_height_cm,aspect_ratio:profile.aspect_ratio,halftone:profile.halftone,allow_internal_nesting:profile.allow_internal_nesting,rotation_policy:profile.rotation_policy,ready_for_print:profile.ready_for_print,created_by:user(),updated_by:user()});if(error)ctx.toast('A cópia foi salva. Abra Medida de produção para cadastrar sua liberação.','err')}
    assertActive(signal);await ctx.logEvent(duplicate?'asset_duplicated':'asset_edited',`${duplicate?'Duplicou':'Editou'} arte com remoção manual de cor`,{workspaceId:asset.workspace_id,projectId:asset.project_id,entityType:'asset',entityId:id,metadata:{source_asset_id:asset.id,removed_colors:rules.length}});
    return response.data;
  }
  return {openMockup,openEditor,openGarment:(asset=null,options={})=>openGarmentComposer(ctx,asset,options),listGarmentDrafts:()=>createGarmentCloudStore(ctx).list()};
}
