const html=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cm=value=>(value/10).toLocaleString('pt-BR',{maximumFractionDigits:2});
const num=value=>Number(String(value).replace(',','.'));

/** Purely local editing: every movement is validated before the layout changes. */
export function mountFilmPreview({element,layout,items,publicUrl,validate,onChange,onRepack,onDelete}){
  let selected=null,zoom=1,background='check',touchMove=false,busy=false,drag=null;
  const itemMap=new Map(items.map(item=>[item.localId,item]));
  element.parentElement.parentElement.querySelector('#filmInspector')?.remove();
  const inspector=document.createElement('section');inspector.id='filmInspector';inspector.className='film-inspector';
  inspector.innerHTML='<div class="film-inspector-head"><div><b>Revise o encaixe</b><small>Toque em uma arte para selecionar. Delete/Backspace exclui a peça selecionada.</small></div><button class="btn small" data-touch-move aria-pressed="false">Rolar / navegar</button><label>Fundo <select data-background aria-label="Fundo de visualização"><option value="check">Transparente</option><option value="white">Branco</option><option value="black">Preto</option><option value="gray">Cinza</option></select></label><label>Zoom <input data-zoom type="range" min="70" max="400" value="100" aria-label="Zoom do filme"></label></div><div class="film-selection-controls" hidden><span data-selected></span><label>X (cm)<input data-x inputmode="decimal"></label><label>Y (cm)<input data-y inputmode="decimal"></label><button class="btn small" data-position>Aplicar posição</button><button class="btn small" data-rotate>Girar</button><button class="btn small" data-lock>Travar</button><button class="btn small film-delete-selected" data-delete>Excluir selecionado</button></div><div class="film-inspector-foot"><span data-help aria-live="polite">O espaço mínimo entre artes é preservado. Arraste apenas pela própria arte.</span><button class="btn small" data-repack>Reotimizar livres</button></div>';
  element.parentElement.insertAdjacentElement('afterend',inspector);
  const get=selector=>inspector.querySelector(selector),key=p=>`${p.id}:${p.copy}`,placement=()=>layout.placements.find(p=>key(p)===selected),scale=()=>Math.min(1.2,700/layout.filmWidthMm)*zoom;
  const snap=value=>Math.round(value/(layout.cellMm||2))*(layout.cellMm||2);
  const status=(message,error=false)=>{get('[data-help]').textContent=message;get('[data-help]').classList.toggle('error',error)};
  const setBusy=value=>{busy=value;inspector.querySelectorAll('button,input,select').forEach(control=>control.disabled=value);element.classList.toggle('is-validating',value);if(!value)updateSelection()};
  const sourceSize=p=>{const item=itemMap.get(p.id);return {width:p.sourceWidthMm||item?.widthCm*10||(p.rotation%180===90?p.heightMm:p.widthMm),height:p.sourceHeightMm||item?.heightCm*10||(p.rotation%180===90?p.widthMm:p.heightMm)}};
  function imageMarkup(p){const item=itemMap.get(p.id),url=item?.type==='asset'&&item.path?publicUrl(item.path):item?.previewDataUrl;if(!url)return `<span class="film-placement-fallback">${html(p.label)}</span>`;const size=sourceSize(p),s=scale();return `<img src="${html(url)}" alt="${html(p.label)}" draggable="false" decoding="async" style="width:${size.width*s}px;height:${size.height*s}px;image-rendering:auto;transform:translate(-50%,-50%) rotate(${p.rotation||0}deg)">`}
  function render(){const s=scale(),height=Math.max(260,layout.lengthMm*s+50);element.style.width=`${layout.filmWidthMm*s+52}px`;element.style.height=`${height}px`;element.innerHTML=`<div class="film-ruler-x">${cm(layout.filmWidthMm)} cm · ${cm(layout.lengthMm)} cm de comprimento</div><div class="film-sheet" data-background="${background}" style="left:42px;top:30px;width:${layout.filmWidthMm*s}px;height:${layout.lengthMm*s}px">${layout.placements.map(p=>`<div class="film-placement visual-placement ${key(p)===selected?'selected':''} ${p.locked?'locked':''}" data-placement="${html(key(p))}" role="button" tabindex="0" aria-label="${html(p.label)}; ${p.locked?'travada':'livre'}; ${cm(p.widthMm)} por ${cm(p.heightMm)} centímetros" aria-pressed="${key(p)===selected}" style="left:${p.xMm*s}px;top:${p.yMm*s}px;width:${p.widthMm*s}px;height:${p.heightMm*s}px">${imageMarkup(p)}<small>${p.locked?'▣ ':''}${cm(sourceSize(p).width)} × ${cm(sourceSize(p).height)}${p.rotation?' · '+p.rotation+'°':''}</small></div>`).join('')}</div>`;bind();updateSelection()}
  function updateSelection(){const p=placement(),controls=get('.film-selection-controls');controls.hidden=!p;if(!p)return;const size=sourceSize(p);get('[data-selected]').textContent=`${p.label} · ${cm(size.width)} × ${cm(size.height)} cm`;get('[data-x]').value=cm(p.xMm);get('[data-y]').value=cm(p.yMm);get('[data-lock]').textContent=p.locked?'Destravar':'Travar';get('[data-position]').disabled=busy||p.locked;get('[data-rotate]').disabled=busy||p.locked||!allowedRotations(p).length;get('[data-delete]').disabled=busy;get('[data-x]').disabled=get('[data-y]').disabled=busy||p.locked;get('[data-angle]').value=String(p.rotation||0).replace('.',',');get('[data-angle]').disabled=get('[data-apply-angle]').disabled=busy||p.locked||!layout.freeRotation||itemMap.get(p.id)?.rotationPolicy==='none';get('[data-angle-label]').hidden=get('[data-apply-angle]').hidden=!layout.freeRotation}
  function allowedRotations(p){const policy=itemMap.get(p.id)?.rotationPolicy||'none';return layout.freeRotation&&policy!=='none'?Array.from({length:12},(_,i)=>i*30):policy==='free'?[0,90,180,270]:policy==='90'?[0,90]:policy==='180'?[0,180]:[]}
  async function attempt(candidate,magnet=null){if(busy)return;setBusy(true);try{const next=await validate(candidate,magnet);layout=next;onChange(next);status('Encaixe validado: medidas, limites e distância preservados.')}catch(error){status(error.message||'Posição inválida. A arte voltou à posição anterior.',true)}finally{setBusy(false);render()}}
  function move(x,y){const p=placement();if(!p||p.locked||!Number.isFinite(x+y))return;attempt(layout.placements.map(current=>key(current)===selected?{...current,xMm:snap(x),yMm:snap(y)}:{...current}),{id:p.id,copy:p.copy})}
  async function removeSelected(){const p=placement();if(!p||busy||typeof onDelete!=='function')return;setBusy(true);try{await onDelete({...p});selected=null;status('Peça removida. O filme foi recalculado.')}catch(error){status(error.message||'Não foi possível excluir a peça.',true)}finally{setBusy(false)}}
  function select(value){selected=value;element.querySelectorAll('[data-placement]').forEach(node=>{node.classList.toggle('selected',node.dataset.placement===value);node.setAttribute('aria-pressed',String(node.dataset.placement===value))});updateSelection()}
  function bind(){element.querySelectorAll('[data-placement]').forEach(node=>{
    node.onpointerdown=event=>{if(busy||event.button!==0)return;select(node.dataset.placement);node.focus({preventScroll:true});const p=placement();if(p.locked||event.pointerType==='touch'&&!touchMove)return;event.preventDefault();node.setPointerCapture(event.pointerId);drag={id:event.pointerId,node,x:event.clientX,y:event.clientY,px:p.xMm,py:p.yMm};};
    node.onpointermove=event=>{if(!drag||drag.id!==event.pointerId)return;const x=snap(drag.px+(event.clientX-drag.x)/scale()),y=snap(drag.py+(event.clientY-drag.y)/scale());node.style.left=`${x*scale()}px`;node.style.top=`${y*scale()}px`;get('[data-x]').value=cm(x);get('[data-y]').value=cm(y)};
    node.onpointerup=event=>{if(!drag||drag.id!==event.pointerId)return;const {px,py,x,y}=drag;drag=null;move(px+(event.clientX-x)/scale(),py+(event.clientY-y)/scale())};node.onpointercancel=()=>{drag=null;render()};
    node.onkeydown=event=>{select(node.dataset.placement);if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();void removeSelected();return}if(event.key==='Enter'||event.key===' '){event.preventDefault();return}const p=placement(),step=layout.cellMm||2,direction={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]}[event.key];if(direction){event.preventDefault();move(p.xMm+direction[0],p.yMm+direction[1])}};
  })}
  get('[data-touch-move]').onclick=()=>{touchMove=!touchMove;element.classList.toggle('touch-move-enabled',touchMove);get('[data-touch-move]').textContent=touchMove?'Mover artes · ativo':'Rolar / navegar';get('[data-touch-move]').setAttribute('aria-pressed',String(touchMove));status(touchMove?'Arraste as artes para reposicionar. Toque em Rolar / navegar ao terminar.':'No celular, deslize livremente para rolar. Ative Mover artes para arrastar uma estampa.')};
  get('[data-background]').onchange=event=>{background=event.target.value;render()};
  get('[data-zoom]').oninput=event=>{zoom=Number(event.target.value)/100;render()};
  get('[data-position]').onclick=()=>move(num(get('[data-x]').value)*10,num(get('[data-y]').value)*10);
  get('[data-lock]').onclick=()=>{const p=placement();if(!p||busy)return;p.locked=!p.locked;onChange(layout);status(p.locked?'Arte travada: sua posição será preservada ao reotimizar.':'Arte destravada.');render()};
  get('[data-delete]').onclick=()=>void removeSelected();
  function rotate(rotation){const p=placement();if(!p||p.locked||!Number.isFinite(rotation))return;rotation=((rotation%360)+360)%360;const size=sourceSize(p),bounds=rotatedBoundsMm(size.width,size.height,rotation);if(bounds.widthMm>layout.filmWidthMm)return status('Nesse ângulo a arte não cabe na largura do filme, sem reduzir o tamanho.',true);attempt(layout.placements.map(current=>key(current)===selected?{...current,...bounds,rotation,sourceWidthMm:size.width,sourceHeightMm:size.height,xMm:Math.max(0,Math.min(p.xMm,Math.floor((layout.filmWidthMm-bounds.widthMm)/(layout.cellMm||2))*(layout.cellMm||2)))}:{...current}))}
  get('[data-rotate]').onclick=()=>{const p=placement();if(!p||p.locked)return;const rotations=allowedRotations(p);if(rotations.length)rotate(rotations[(rotations.indexOf(p.rotation)+1)%rotations.length])};
  get('[data-rotate]').insertAdjacentHTML('afterend','<label data-angle-label hidden>Ângulo (°)<input data-angle inputmode="decimal" aria-label="Ângulo da arte"></label><button class="btn small" data-apply-angle hidden>Aplicar ângulo</button>');
  get('[data-apply-angle]').onclick=()=>{const value=num(get('[data-angle]').value);if(!Number.isFinite(value))return status('Informe um ângulo válido em graus.',true);rotate(value)};
  get('[data-repack]').onclick=async()=>{if(busy)return;setBusy(true);status('Recalculando as artes livres…');try{const next=await onRepack(layout.placements.filter(p=>p.locked));layout=next;onChange(next);status('Artes livres reorganizadas. Posições travadas preservadas.')}catch(error){status(error.message,true)}finally{setBusy(false);render()}};
  render();return {getLayout:()=>layout,deleteSelected:removeSelected};
}
import {rotatedBoundsMm} from './nesting-core.js?v=2.17.3';
