import {replacePreviewMarkup} from './asset-preview.js?v=2.17.9';

const html=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cm=value=>(value/10).toLocaleString('pt-BR',{maximumFractionDigits:2});
const num=value=>Number(String(value).replace(',','.'));

/** Purely local editing: every movement is validated before the layout changes. */
export function mountFilmPreview({element,layout,items,publicUrl,validate,onChange,onRepack,onDelete,isCurrent=()=>true}){
  if(!element||!layout||!Array.isArray(layout.placements)||!(layout.filmWidthMm>0))return {getLayout:()=>null,deleteSelected:async()=>{}};
  let selected=null,zoom=1,background='check',touchMove=false,busy=false,drag=null;
  const itemMap=new Map(items.map(item=>[item.localId,item]));
  element.classList.remove('is-validating','touch-move-enabled');
  element.parentElement.parentElement.querySelector('#filmInspector')?.remove();
  const inspector=document.createElement('section');inspector.id='filmInspector';inspector.className='film-inspector';
  inspector.innerHTML='<div class="film-inspector-head"><div><b>Ajustar encaixe</b><small>Toque em uma arte para selecionar. Arraste para mover; o sistema valida o espaço automaticamente.</small></div><button class="btn small" data-touch-move aria-pressed="false">Rolar / navegar</button><label>Fundo <select data-background aria-label="Fundo de visualização"><option value="check">Transparente</option><option value="white">Branco</option><option value="black">Preto</option><option value="gray">Cinza</option></select></label><label>Zoom <input data-zoom type="range" min="70" max="400" value="100" aria-label="Zoom do filme"></label></div><div class="film-selection-controls" hidden><span data-selected></span><div class="film-angle-presets" aria-label="Girar arte"><button class="btn small" data-angle-preset="0">0°</button><button class="btn small" data-angle-preset="90">90°</button><button class="btn small" data-angle-preset="180">180°</button><button class="btn small" data-angle-preset="270">270°</button></div><label class="film-angle-input">Ângulo livre (°)<input data-angle inputmode="decimal" aria-label="Ângulo da arte"></label><button class="btn small" data-rotate>Girar 90°</button><button class="btn small" data-lock>Travar</button><button class="btn small film-delete-selected" data-delete>Excluir selecionado</button></div><div class="film-inspector-foot"><span data-help aria-live="polite">Mover, girar ou travar é opcional. O objetivo automático é usar o mínimo possível de comprimento.</span><button class="btn small" data-repack>Otimizar espaços</button></div>';
  element.parentElement.insertAdjacentElement('afterend',inspector);
  const active=()=>element.isConnected!==false&&inspector.isConnected!==false&&isCurrent();
  const get=selector=>inspector.querySelector(selector),key=p=>`${p.id}:${p.copy}`,placement=()=>layout?.placements?.find(p=>key(p)===selected),scale=()=>Math.min(1.2,700/layout.filmWidthMm)*zoom;
  const snap=value=>Math.round(value/(layout.cellMm||2))*(layout.cellMm||2);
  const status=(message,error=false)=>{if(!active())return;get('[data-help]').textContent=message;get('[data-help]').classList.toggle('error',error)};
  const setBusy=value=>{busy=value;inspector.querySelectorAll('button,input,select').forEach(control=>control.disabled=value);element.classList.toggle('is-validating',value);if(!value)updateSelection()};
  const sourceSize=p=>{const item=itemMap.get(p.id);return {width:p.sourceWidthMm||item?.widthCm*10||(p.rotation%180===90?p.heightMm:p.widthMm),height:p.sourceHeightMm||item?.heightCm*10||(p.rotation%180===90?p.widthMm:p.heightMm)}};
  function imageMarkup(p){const item=itemMap.get(p.id),url=item?.type==='asset'&&item.path?publicUrl(item.path):item?.previewDataUrl;if(!url)return `<span class="film-placement-fallback">${html(p.label)}</span>`;const size=sourceSize(p),s=scale();return `<img src="${html(url)}" alt="${html(p.label)}" draggable="false" decoding="async" style="width:${size.width*s}px;height:${size.height*s}px;image-rendering:auto;transform:translate(-50%,-50%) rotate(${p.rotation||0}deg)">`}
  function render(){if(!active()||!layout?.placements)return;const s=scale(),height=Math.max(260,layout.lengthMm*s+50);element.style.width=`${layout.filmWidthMm*s+52}px`;element.style.height=`${height}px`;replacePreviewMarkup(element,`<div class="film-ruler-x">${cm(layout.filmWidthMm)} cm · ${cm(layout.lengthMm)} cm de comprimento</div><div class="film-sheet" data-background="${background}" style="left:42px;top:30px;width:${layout.filmWidthMm*s}px;height:${layout.lengthMm*s}px">${layout.placements.map(p=>`<div class="film-placement visual-placement ${key(p)===selected?'selected':''} ${p.locked?'locked':''}" data-placement="${html(key(p))}" role="button" tabindex="0" aria-label="${html(p.label)}; ${p.locked?'travada':'livre'}; ${cm(p.widthMm)} por ${cm(p.heightMm)} centímetros" aria-pressed="${key(p)===selected}" style="left:${p.xMm*s}px;top:${p.yMm*s}px;width:${p.widthMm*s}px;height:${p.heightMm*s}px">${imageMarkup(p)}<small>${p.locked?'▣ ':''}${cm(sourceSize(p).width)} × ${cm(sourceSize(p).height)}${p.rotation?' · '+p.rotation+'°':''}</small></div>`).join('')}</div>`);bind();updateSelection()}
  function updateSelection(){const p=placement(),controls=get('.film-selection-controls');controls.hidden=!p;if(!p)return;const size=sourceSize(p);get('[data-selected]').textContent=`${p.label} · ${cm(size.width)} × ${cm(size.height)} cm`;get('[data-lock]').textContent=p.locked?'Destravar':'Travar';get('[data-rotate]').disabled=busy||p.locked;get('[data-delete]').disabled=busy;get('[data-angle]').value=String(p.rotation||0).replace('.',',');get('[data-angle]').disabled=busy||p.locked;inspector.querySelectorAll('[data-angle-preset]').forEach(button=>{button.disabled=busy||p.locked;button.classList.toggle('active',Number(button.dataset.anglePreset)===Number(p.rotation||0))})}
  function allowedRotations(){return [0,90,180,270]}
  async function attempt(candidate,magnet=null,validationOptions={}){if(busy||!active())return;setBusy(true);try{const next=await validate(candidate,magnet,validationOptions);if(!active()||!next?.placements)return;if(onChange(next)===false)return;layout=next;status('Encaixe validado: medidas, limites e distância preservados.')}catch(error){if(active())status(error.message||'Posição inválida. A arte voltou à posição anterior.',true)}finally{if(active()){setBusy(false);render()}}}
  function move(x,y){const p=placement();if(!p||p.locked||!Number.isFinite(x+y))return;attempt(layout.placements.map(current=>key(current)===selected?{...current,xMm:snap(x),yMm:snap(y)}:{...current}),{id:p.id,copy:p.copy})}
  async function removeSelected(){const p=placement();if(!p||busy||!active()||typeof onDelete!=='function')return;setBusy(true);try{await onDelete({...p});if(!active())return;selected=null;status('Peça removida. As demais posições foram preservadas.')}catch(error){if(active())status(error.message||'Não foi possível excluir a peça.',true)}finally{if(active())setBusy(false)}}
  function select(value){selected=value;element.querySelectorAll('[data-placement]').forEach(node=>{node.classList.toggle('selected',node.dataset.placement===value);node.setAttribute('aria-pressed',String(node.dataset.placement===value))});updateSelection()}
  function bind(){element.querySelectorAll('[data-placement]').forEach(node=>{
    node.onpointerdown=event=>{if(busy||event.button!==0)return;select(node.dataset.placement);node.focus({preventScroll:true});const p=placement();if(p.locked||event.pointerType==='touch'&&!touchMove)return;event.preventDefault();node.setPointerCapture(event.pointerId);drag={id:event.pointerId,node,x:event.clientX,y:event.clientY,px:p.xMm,py:p.yMm};};
    node.onpointermove=event=>{if(!drag||drag.id!==event.pointerId)return;const x=snap(drag.px+(event.clientX-drag.x)/scale()),y=snap(drag.py+(event.clientY-drag.y)/scale());node.style.left=`${x*scale()}px`;node.style.top=`${y*scale()}px`};
    node.onpointerup=event=>{if(!drag||drag.id!==event.pointerId)return;const {px,py,x,y}=drag;drag=null;move(px+(event.clientX-x)/scale(),py+(event.clientY-y)/scale())};node.onpointercancel=()=>{drag=null;render()};
    node.onkeydown=event=>{select(node.dataset.placement);if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();void removeSelected();return}if(event.key==='Enter'||event.key===' '){event.preventDefault();return}const p=placement(),step=layout.cellMm||2,direction={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]}[event.key];if(direction){event.preventDefault();move(p.xMm+direction[0],p.yMm+direction[1])}};
  })}
  get('[data-touch-move]').onclick=()=>{touchMove=!touchMove;element.classList.toggle('touch-move-enabled',touchMove);get('[data-touch-move]').textContent=touchMove?'Mover artes · ativo':'Rolar / navegar';get('[data-touch-move]').setAttribute('aria-pressed',String(touchMove));status(touchMove?'Arraste as artes para reposicionar. Toque em Rolar / navegar ao terminar.':'No celular, deslize livremente para rolar. Ative Mover artes para arrastar uma estampa.')};
  get('[data-background]').onchange=event=>{background=event.target.value;render()};
  get('[data-zoom]').oninput=event=>{zoom=Number(event.target.value)/100;render()};
  get('[data-lock]').onclick=()=>{const p=placement();if(!p||busy)return;p.locked=!p.locked;onChange(layout);status(p.locked?'Arte travada: sua posição será preservada ao reotimizar.':'Arte destravada.');render()};
  get('[data-delete]').onclick=()=>void removeSelected();
  function rotate(rotation,{free=false}={}){const p=placement();if(!p||p.locked||!Number.isFinite(rotation))return;rotation=((rotation%360)+360)%360;const size=sourceSize(p),bounds=rotatedBoundsMm(size.width,size.height,rotation);if(bounds.widthMm>layout.filmWidthMm)return status('Nesse ângulo a arte não cabe na largura do filme, sem reduzir o tamanho.',true);attempt(layout.placements.map(current=>key(current)===selected?{...current,...bounds,rotation,sourceWidthMm:size.width,sourceHeightMm:size.height,xMm:Math.max(0,Math.min(p.xMm,Math.floor((layout.filmWidthMm-bounds.widthMm)/(layout.cellMm||2))*(layout.cellMm||2)))}:{...current}),null,free?{allowFreeRotation:true}:{})}
  get('[data-rotate]').onclick=()=>{const p=placement();if(!p||p.locked)return;const rotations=allowedRotations(),current=rotations.includes(Number(p.rotation))?rotations.indexOf(Number(p.rotation)):-1;rotate(rotations[(current+1)%rotations.length])};
  inspector.querySelectorAll('[data-angle-preset]').forEach(button=>button.onclick=()=>rotate(Number(button.dataset.anglePreset)));
  get('[data-angle]').onchange=()=>{const value=num(get('[data-angle]').value);if(!Number.isFinite(value))return status('Informe um ângulo válido em graus.',true);rotate(value,{free:value%90!==0})};
  get('[data-angle]').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();get('[data-angle]').blur()}};
  get('[data-repack]').onclick=async()=>{if(busy||!active())return;setBusy(true);status('Procurando um encaixe menor sem mexer nas posições travadas…');try{const next=await onRepack(layout.placements.filter(p=>p.locked));if(!active()||!next?.placements)return;if(onChange(next)===false)return;layout=next;status(next.nestingSearchWarning||next.rotationSearchWarning||'Espaços otimizados. As posições travadas foram preservadas.')}catch(error){if(active())status(error.message,true)}finally{if(active()){setBusy(false);render()}}};
  render();return {getLayout:()=>layout,deleteSelected:removeSelected};
}
import {rotatedBoundsMm} from './nesting-core.js?v=2.17.3';
