import {normalizeGarmentScene,GARMENT_DEFAULTS} from './garment-scene.js?v=2.17.3';
import {garmentColor,garmentPalette} from './garment-colors.js?v=2.17.11';

const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colorValue=scene=>Number.parseInt(garmentColor(scene).hex.slice(1),16);
const names={front:'Frente',back:'Costas',left:'Manga esquerda',right:'Manga direita'};
const tick=()=>new Promise(resolve=>requestAnimationFrame(resolve));
const smooth=(start,end,value)=>{const t=Math.max(0,Math.min(1,(value-start)/(end-start)));return t*t*(3-2*t)};

// A disclosed derivative of the licensed oversized mesh, not a second scan.
// Continuous deformation leaves the collar/torso center untouched and reduces
// only the dropped-shoulder/distal sleeve region, preserving volumetric depth.
export function regularGarmentPoint(x,y,z,{bodyWidth,bodyLength}){
  const half=bodyWidth/2,q=Math.abs(x)/half,t=y/bodyLength+.5;
  const sleeve=smooth(.73,1.3,q)*smooth(.42,.69,t),shoulder=smooth(.42,.85,q)*(1-smooth(.92,1.2,q))*smooth(.76,.96,t);
  return [Math.sign(x)*(Math.abs(x)-sleeve*Math.max(0,Math.abs(x)-half*.63)*.20),y+sleeve*bodyLength*.043+shoulder*bodyLength*.021,z*(1-sleeve*.18)];
}
// Optional preview refinement, preserving the lower-body calibration and depth.
// This is a disclosed artistic deformation, never a cloth-physics simulation.
export function relaxedGarmentPoint(x,y,z,{bodyWidth,bodyLength},model='oversized'){
  const q=Math.abs(x)/(bodyWidth/2),t=y/bodyLength+.5;
  const shoulder=smooth(.28,1.05,q)*smooth(.57,.89,t),drop=bodyLength*(model==='normal'?.073:.049)*shoulder;
  const neck=(1-smooth(.08,.36,q))*smooth(.91,.99,t)*smooth(-1,5,z)*bodyLength*.035;
  return [x,y-drop-neck,z];
}
export function garmentCameraDistance({width,height,depth,aspect,fov=35,side='front'}){
  const span=side==='left'||side==='right'?depth:width,vertical=height+depth*.025;
  return Math.max(vertical,span/Math.max(.05,aspect))/(2*Math.tan(fov*Math.PI/360))/.86+depth*.35;
}
export function garmentSnapshotSize(width,height){if(!(Number.isFinite(width)&&Number.isFinite(height)&&width>0&&height>0))throw new Error('Dimensões da vista inválidas.');const scale=Math.min(2000/width,1910/height);return {width:Math.max(1,Math.round(width*scale)),height:Math.max(1,Math.round(height*scale)),creditHeight:90}}

/** Real, isolated WebGL viewer. The source scene and artwork files are never changed. */
export async function openGarment3D(ctx,source,options={}){
  const refinedDrape=options.refinedDrape!==false;
  let design=normalizeGarmentScene(source),closed=false,sharing=false,renderer,controls,world,camera,THREE,modelGroup,decals,frameId=0,resizeObserver,generation=0,manifest,userAdjustedView=false;
  const previous=document.activeElement,oldOverflow=document.body.style.overflow,abort=new AbortController(),textures=new Set(),geometries=new Set(),materials=new Set(),bitmaps=new Set();
  let resolveDone;const done=new Promise(resolve=>{resolveDone=resolve});
  const root=document.createElement('div');root.className='garment-3d-backdrop';
  root.innerHTML=`<section class="garment-3d" role="dialog" aria-modal="true" aria-label="Camiseta em 3D"><header><div><span class="g3-eyebrow">ZERO 19 / 3D REAL</span><h2>${escape(design.title)}</h2></div><button class="g3-close" aria-label="Fechar visualização 3D">×</button></header><div class="g3-toolbar"><label>Modelo<select data-g3-model aria-label="Modelo 3D" disabled><option>Carregando modelos…</option></select></label><div class="g3-colors" aria-label="Cor da camiseta">${garmentPalette(design).map(color=>`<button data-g3-color="${color.id}" title="${escape(color.name)}" aria-label="${escape(color.name)}" style="--color:${color.hex}"></button>`).join('')}</div><button data-g3-reset>Redefinir vista</button></div><div class="g3-viewport"><div class="g3-loading" role="status">Preparando visualização 3D…</div></div><nav class="g3-views" aria-label="Vistas da camiseta">${Object.entries(names).map(([key,label])=>`<button data-g3-view="${key}">${label}</button>`).join('')}</nav><div class="g3-status" role="status" aria-live="polite"></div><footer><div><b>Arraste para girar · pinça ou roda para aproximar</b><p>Simulação de caimento. Escala aproximada e projeção sobre a malha; confira medidas e posições no editor 2D. PNG de apresentação, não arquivo DTF.</p><small class="g3-credit"></small></div><div class="g3-footer-actions">${typeof options.onShare==='function'?'<button data-g3-share>Link 3D</button>':''}<button class="g3-primary" data-g3-export disabled>Baixar vista 3D</button></div></footer></section>`;
  document.body.append(root);document.body.style.overflow='hidden';
  const footerInfo=root.querySelector('footer>div'),about=document.createElement('details');about.className='g3-about';about.innerHTML='<summary>Modelo, licença e limites de escala</summary>';about.append(footerInfo.querySelector('p'),footerInfo.querySelector('.g3-credit'));footerInfo.append(about);const disclaimer=document.createElement('span');disclaimer.className='g3-disclaimer';disclaimer.textContent='Prévia ilustrativa · não é arquivo DTF';footerInfo.append(disclaimer);
  const find=selector=>root.querySelector(selector),status=(text,error=false)=>{if(closed)return;find('.g3-status').textContent=text;find('.g3-status').classList.toggle('error',error)};
  const active=token=>{if(closed||abort.signal.aborted||token!==generation)throw new DOMException('Visualização encerrada.','AbortError')};
  function dispose(){cancelAnimationFrame(frameId);resizeObserver?.disconnect();controls?.dispose();for(const geometry of geometries)geometry.dispose();for(const material of materials)material.dispose();for(const texture of textures)texture.dispose();for(const bitmap of bitmaps)bitmap.close?.();geometries.clear();materials.clear();textures.clear();bitmaps.clear();renderer?.dispose();renderer?.forceContextLoss();if(renderer){renderer.domElement.width=renderer.domElement.height=1}world?.clear()}
  function close(force=false){if(closed||sharing&&!force)return;closed=true;generation++;abort.abort();window.removeEventListener('z19:account-changing',accountChanged);options.signal?.removeEventListener('abort',accountChanged);dispose();root.remove();document.body.style.overflow=force?'':oldOverflow;if(!force&&previous?.isConnected)previous.focus({preventScroll:true});try{options.onClose?.()}finally{resolveDone()}}
  const accountChanged=()=>close(true);window.addEventListener('z19:account-changing',accountChanged);
  options.signal?.addEventListener('abort',accountChanged,{once:true});
  const controller={close,done,element:root};find('.g3-close').onclick=()=>close();root.addEventListener('click',event=>{if(event.target===root)close()});
  root.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();close();return}if(event.key!=='Tab')return;const nodes=[...root.querySelectorAll('button:not([disabled]),select:not([disabled]),summary,a[href],canvas')].filter(node=>node.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}});find('.g3-close').focus();
  find('[data-g3-share]')?.addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;sharing=true;find('.garment-3d').inert=true;try{await options.onShare(normalizeGarmentScene(design))}catch(error){status(error.message||'Não foi possível compartilhar.',true)}finally{sharing=false;if(!closed){find('.garment-3d').inert=false;button.disabled=false;button.focus()}}});
  const viewport=find('.g3-viewport');
  let GLTFLoader,OrbitControls,DecalGeometry,meshes=[],modelBounds,cmHeight=design.measurements.bodyLength;
  function trackTexture(texture){if(!texture)return; textures.add(texture);if(texture.source?.data?.close)bitmaps.add(texture.source.data)}
  function resize(){if(!renderer||closed)return;const {width,height}=viewport.getBoundingClientRect();renderer.setSize(Math.max(1,width),Math.max(1,height),false);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix();if(!userAdjustedView&&modelBounds)view(viewport.dataset.view||'front');else render()}
  function render(){if(!renderer||closed)return;renderer.render(world,camera)}
  function view(side='front'){if(!camera||!modelBounds)return;userAdjustedView=false;const size=modelBounds.getSize(new THREE.Vector3()),distance=garmentCameraDistance({width:size.x,height:size.y,depth:size.z,aspect:camera.aspect,fov:camera.fov,side}),target=modelBounds.getCenter(new THREE.Vector3()),directions={front:[0,.025,1],back:[0,.025,-1],left:[1,.02,.06],right:[-1,.02,.06]};camera.position.copy(new THREE.Vector3(...directions[side]).normalize().multiplyScalar(distance).add(target));controls.target.copy(target);controls.minDistance=size.y*.65;controls.maxDistance=Math.max(size.y*4,distance*2);controls.update();viewport.dataset.view=side;render()}
  function applyColor(){for(const mesh of meshes)mesh.material.color.setHex(colorValue(design));root.querySelectorAll('[data-g3-color]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.g3Color===design.color)));render()}
  function clearModel(){if(modelGroup){world.remove(modelGroup);modelGroup.traverse(node=>{if(node.geometry){node.geometry.dispose();geometries.delete(node.geometry)}if(node.material){node.material.dispose();materials.delete(node.material)}})}if(decals){world.remove(decals);decals.traverse(node=>{if(node.geometry){node.geometry.dispose();geometries.delete(node.geometry)}if(node.material){node.material.dispose();materials.delete(node.material)}})}for(const texture of textures)texture.dispose();for(const bitmap of bitmaps)bitmap.close?.();textures.clear();bitmaps.clear();meshes=[];modelGroup=null;decals=null;delete root.dataset.ready}
  async function artTexture(path,token){const response=await fetch(ctx.publicUrl?ctx.publicUrl(path):path,{signal:abort.signal,credentials:'omit'});if(!response.ok)throw new Error('Uma estampa não pôde ser carregada.');const blob=await response.blob();active(token);let bitmap=await createImageBitmap(blob,{imageOrientation:'flipY'});if(closed||token!==generation){bitmap.close();active(token)}const limit=Math.max(256,Math.min(2048,Math.floor(Math.sqrt(12e6/Math.max(1,new Set(design.layers.map(layer=>layer.path)).size)))));if(Math.max(bitmap.width,bitmap.height)>limit){const scale=limit/Math.max(bitmap.width,bitmap.height),small=await createImageBitmap(bitmap,{resizeWidth:Math.max(1,Math.round(bitmap.width*scale)),resizeHeight:Math.max(1,Math.round(bitmap.height*scale)),resizeQuality:'high'});bitmap.close();bitmap=small;if(closed||token!==generation){bitmap.close();active(token)}}bitmaps.add(bitmap);const texture=new THREE.Texture(bitmap);texture.needsUpdate=true;texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());textures.add(texture);return texture}
  function projection(layer){const height=layer.width/layer.ratio,measure=design.measurements;let x,y,z,normal,orientation;
    if(layer.side==='front'||layer.side==='back'){const back=layer.side==='back';x=(layer.x-measure.bodyWidth/2)*(back?-1:1);y=cmHeight/2-layer.y;z=(back?modelBounds.min.z:modelBounds.max.z)+(back?-cmHeight:cmHeight);normal=new THREE.Vector3(0,0,back?-1:1);orientation=new THREE.Euler(0,back?Math.PI:0,0)}
    else{const left=layer.side==='left';x=(left?modelBounds.max.x:modelBounds.min.x)+(left?cmHeight:-cmHeight);y=cmHeight/2-cmHeight*.17-layer.y*(cmHeight*.36/measure.sleeveLength);z=(measure.sleeveWidth/2-layer.x)*(left?1:-1);normal=new THREE.Vector3(left?1:-1,0,0);orientation=new THREE.Euler(0,left?Math.PI/2:-Math.PI/2,0)}
    const ray=new THREE.Raycaster(new THREE.Vector3(x,y,z),normal.clone().negate()),hit=ray.intersectObjects(meshes,false).find(result=>{const n=result.face?.normal?.clone().transformDirection(result.object.matrixWorld);return n&&n.dot(normal)>.05});if(!hit)return null;
    return {position:hit.point.clone().addScaledVector(normal,.015),normal,orientation,size:new THREE.Vector3(layer.width,height,Math.max(5,Math.min(cmHeight*.25,layer.width*.8)))};
  }
  function outwardGeometry(mesh,p){const geometry=new DecalGeometry(mesh,p.position,p.orientation,p.size),positions=geometry.getAttribute('position'),normals=geometry.getAttribute('normal'),uv=geometry.getAttribute('uv'),out={position:[],normal:[],uv:[]};for(let index=0;index<positions.count;index+=3){let dot=0;for(let n=0;n<3;n++)dot+=normals.getX(index+n)*p.normal.x+normals.getY(index+n)*p.normal.y+normals.getZ(index+n)*p.normal.z;if(dot<=.15)continue;for(let n=0;n<3;n++){out.position.push(positions.getX(index+n),positions.getY(index+n),positions.getZ(index+n));out.normal.push(normals.getX(index+n),normals.getY(index+n),normals.getZ(index+n));out.uv.push(uv.getX(index+n),uv.getY(index+n))}}geometry.dispose();if(!out.position.length)return null;const filtered=new THREE.BufferGeometry();filtered.setAttribute('position',new THREE.Float32BufferAttribute(out.position,3));filtered.setAttribute('normal',new THREE.Float32BufferAttribute(out.normal,3));filtered.setAttribute('uv',new THREE.Float32BufferAttribute(out.uv,2));return filtered}
  async function loadModel(key){const token=++generation,entry=manifest.models[key];clearModel();find('[data-g3-export]').disabled=true;if(!entry?.path){find('.g3-loading').hidden=false;find('.g3-loading').innerHTML=`<b>Modelo ${key==='normal'?'normal':'oversized'} não disponível em 3D.</b><span>A montagem 2D permanece intacta. Não substituímos um modelo por outro sem você escolher.</span>`;status('Selecione um modelo disponível para experimentar em 3D.',true);return}
    design.model=key;cmHeight=design.measurements.bodyLength;find('.g3-loading').hidden=false;find('.g3-loading').textContent='Carregando a malha real e os materiais…';status('');
    try{const url=new URL(entry.path,document.baseURI),response=await fetch(url,{signal:abort.signal,credentials:'omit'});if(!response.ok)throw new Error('Não foi possível carregar o modelo 3D.');const buffer=await response.arrayBuffer();active(token);const gltf=await new GLTFLoader().parseAsync(buffer,new URL('.',url).href);if(closed||token!==generation){gltf.scene.traverse(node=>{node.geometry?.dispose();if(node.material)for(const material of Array.isArray(node.material)?node.material:[node.material]){for(const value of Object.values(material))if(value?.isTexture){value.dispose();value.source?.data?.close?.()}material.dispose()}});active(token)}gltf.scene.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(gltf.scene),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());if(!(size.y>0))throw new Error('A malha não tem dimensões válidas.');
      // Mid/lower torso excludes the sleeve span; this calibrates centimeters
      // to the user's body width, not to the full width including sleeves.
      let torsoMin=Infinity,torsoMax=-Infinity;const point=new THREE.Vector3();gltf.scene.traverse(node=>{if(!node.isMesh)return;const attribute=node.geometry.getAttribute('position');for(let i=0;i<attribute.count;i+=5){point.fromBufferAttribute(attribute,i).applyMatrix4(node.matrixWorld);const y=(point.y-box.min.y)/size.y;if(y>.2&&y<.5){torsoMin=Math.min(torsoMin,point.x);torsoMax=Math.max(torsoMax,point.x)}}});const bodyWidth=torsoMax-torsoMin,sy=cmHeight/size.y,sx=design.measurements.bodyWidth/(bodyWidth>0?bodyWidth:size.x*.7);modelGroup=new THREE.Group();
      gltf.scene.traverse(node=>{if(!node.isMesh)return;const geometry=node.geometry.clone().applyMatrix4(node.matrixWorld);geometry.translate(-center.x,-center.y,-center.z);geometry.scale(sx,sy,sy);if(entry.adaptation==='regular-from-oversized-v1'||refinedDrape){const attribute=geometry.getAttribute('position');for(let index=0;index<attribute.count;index++){let transformed=[attribute.getX(index),attribute.getY(index),attribute.getZ(index)];if(entry.adaptation==='regular-from-oversized-v1')transformed=regularGarmentPoint(...transformed,design.measurements);if(refinedDrape)transformed=relaxedGarmentPoint(...transformed,design.measurements,key);attribute.setXYZ(index,...transformed)}attribute.needsUpdate=true;geometry.computeVertexNormals();geometry.deleteAttribute('tangent')}geometry.computeBoundingBox();geometries.add(geometry);const original=Array.isArray(node.material)?node.material[0]:node.material,material=new THREE.MeshStandardMaterial({color:colorValue(design),roughness:.85,metalness:0,normalMap:original.normalMap||null,roughnessMap:original.roughnessMap||null,side:THREE.DoubleSide});if(original.normalScale)material.normalScale.copy(original.normalScale);materials.add(material);for(const value of Object.values(original))if(value?.isTexture)trackTexture(value);const mesh=new THREE.Mesh(geometry,material);mesh.name=node.name;modelGroup.add(mesh);meshes.push(mesh);node.geometry.dispose();original.dispose()});world.add(modelGroup);modelGroup.updateMatrixWorld(true);modelBounds=new THREE.Box3().setFromObject(modelGroup);decals=new THREE.Group();world.add(decals);applyColor();view('front');
      const author=entry.author||gltf.asset?.extras?.author||'Autor identificado no arquivo',license=entry.license||gltf.asset?.extras?.license||'',sourceUrl=entry.source||gltf.asset?.extras?.source;find('.g3-credit').innerHTML=`Modelo: ${escape(author)} · ${escape(typeof license==='string'?license:license.name||'')} ${entry.adaptation?'· Normal derivado da malha oversized; não é uma digitalização independente. ':''}${refinedDrape?'· Caimento visual Zero 19: ombros e gola ajustados digitalmente. ':''}${sourceUrl&&/^https:\/\//.test(sourceUrl)?`<a href="${escape(sourceUrl)}" target="_blank" rel="noopener noreferrer">Origem e licença</a>`:''}`;
      let placed=0,unavailable=0;const imageCache=new Map();for(const [index,layer] of design.layers.entries()){active(token);find('.g3-loading').textContent=`Projetando estampa ${index+1} de ${design.layers.length}…`;await tick();active(token);try{const p=projection(layer);if(!p){unavailable++;continue}let texture=imageCache.get(layer.path);if(!texture){texture=await artTexture(layer.path,token);imageCache.set(layer.path,texture)}const material=new THREE.MeshStandardMaterial({map:texture,transparent:true,alphaTest:.015,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2-index*.1,roughness:.82,metalness:0,side:THREE.FrontSide});materials.add(material);let found=false;for(const mesh of meshes){const geometry=outwardGeometry(mesh,p);if(!geometry)continue;geometries.add(geometry);const decal=new THREE.Mesh(geometry,material);decal.renderOrder=10+index;decal.userData={side:layer.side,layerId:layer.id};decals.add(decal);found=true}if(found)placed++;else unavailable++}catch(error){if(error.name==='AbortError')throw error;unavailable++;}render()}
      active(token);find('.g3-loading').hidden=true;find('[data-g3-export]').disabled=false;root.dataset.ready='true';root.dataset.projected=String(placed);root.dataset.missing=String(unavailable);status(unavailable?`${placed} estampa(s) projetada(s); ${unavailable} fora da superfície disponível ou sem imagem. Confira no editor 2D. Projeções podem distorcer perto de costuras e curvas.`:`${placed} estampa(s) sobre a malha real. Medidas aproximadas; curvas e costuras podem distorcer a projeção.`,Boolean(unavailable));render();
    }catch(error){if(error.name==='AbortError')return;find('.g3-loading').hidden=false;find('.g3-loading').textContent='Não foi possível preparar este modelo 3D.';status(error.message||'Falha ao carregar o modelo.',true)}
  }
  try{
    if(options.signal?.aborted){close(true);return controller}
    const modules=await Promise.all([import('./vendor/three/three.module.js'),import('./vendor/three/addons/loaders/GLTFLoader.js'),import('./vendor/three/addons/controls/OrbitControls.js'),import('./vendor/three/addons/geometries/DecalGeometry.js')]);if(closed)return controller;[THREE,{GLTFLoader},{OrbitControls},{DecalGeometry}]=modules;
    const response=await fetch(new URL('./assets/garment3d/manifest.json',import.meta.url),{signal:abort.signal,credentials:'omit'});if(!response.ok)throw new Error('Catálogo de modelos 3D indisponível.');manifest=await response.json();active(generation);if(!manifest?.models)throw new Error('Catálogo 3D inválido.');
    const canvas=document.createElement('canvas');canvas.tabIndex=0;canvas.setAttribute('aria-label','Camiseta tridimensional. Arraste para girar e use pinça para aproximar.');const webgl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true});if(!webgl)throw new Error('WebGL 2 não está disponível neste dispositivo. Use as vistas 2D ou ative a aceleração gráfica do navegador.');renderer=new THREE.WebGLRenderer({canvas,context:webgl,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;viewport.prepend(canvas);world=new THREE.Scene();world.background=new THREE.Color(0x202026);camera=new THREE.PerspectiveCamera(35,1,.05,2000);world.add(new THREE.HemisphereLight(0xffffff,0x747989,2.8));for(const [x,y,z,power] of [[-80,100,100,3.8],[80,50,-90,3.5],[0,-60,100,.8]]){const light=new THREE.DirectionalLight(0xffffff,power);light.position.set(x,y,z);world.add(light)}controls=new OrbitControls(camera,canvas);controls.enableDamping=false;controls.enablePan=false;controls.minPolarAngle=.15;controls.maxPolarAngle=Math.PI-.15;controls.addEventListener('change',render);resizeObserver=new ResizeObserver(resize);resizeObserver.observe(viewport);resize();
    controls.addEventListener('start',()=>{userAdjustedView=true;});
    canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();if(!closed){find('[data-g3-export]').disabled=true;status('A sessão gráfica foi interrompida. Feche e abra o 3D novamente; sua montagem está preservada.',true)}});
    const modelSelect=find('[data-g3-model]');modelSelect.innerHTML=['normal','oversized'].map(key=>`<option value="${key}" ${key===design.model?'selected':''} ${manifest.models[key]?.path?'':'disabled'}>${manifest.models[key]?.adaptation?'Normal · adaptação oversized':key==='normal'?'Normal':'Oversized'}${manifest.models[key]?.path?'':' · indisponível'}</option>`).join('');modelSelect.disabled=Boolean(options.readOnly);modelSelect.onchange=async()=>{design.measurements={...GARMENT_DEFAULTS[modelSelect.value]};await loadModel(modelSelect.value)};
    for(const button of root.querySelectorAll('[data-g3-color]')){button.disabled=Boolean(options.readOnly);button.onclick=()=>{const color=garmentPalette(design).find(value=>value.id===button.dataset.g3Color);if(!color)return;design.color=color.id;design.colorHex=color.hex;design.colorName=color.name;applyColor()}}find('[data-g3-reset]').onclick=()=>view('front');root.querySelectorAll('[data-g3-view]').forEach(button=>button.onclick=()=>view(button.dataset.g3View));
    find('[data-g3-export]').onclick=async event=>{
      const button=event.currentTarget;button.disabled=true;const oldRatio=renderer.getPixelRatio(),oldSize=renderer.getSize(new THREE.Vector2());let presentation;
      try{const {width,height,creditHeight}=garmentSnapshotSize(oldSize.x,oldSize.y);renderer.setPixelRatio(1);renderer.setSize(width,height,false);render();presentation=document.createElement('canvas');presentation.width=width;presentation.height=height+creditHeight;const g=presentation.getContext('2d');if(!g)throw Error('Memória insuficiente para exportar a vista.');g.drawImage(canvas,0,0,width,height);g.fillStyle='#141318';g.fillRect(0,height,width,creditHeight);g.fillStyle='#eee8e3';g.font=`${Math.max(12,Math.min(18,Math.floor(width/95)))}px Arial`;const entry=manifest.models[design.model],lines=['Vista 3D ilustrativa · Não usar como filme DTF.',`Modelo: ${entry.author||'kylelhb'} · ${entry.license||'CC BY 4.0'}${entry.adaptation?' · Normal: adaptação geométrica Zero 19.':''}${refinedDrape?' · Ombros/gola ajustados digitalmente.':' · Cor e estampas aplicadas digitalmente.'}`,entry.source||'https://sketchfab.com/kylelhb'];lines.forEach((line,index)=>g.fillText(line,20,height+24+index*25,width-40));const blob=await new Promise((resolve,reject)=>presentation.toBlob(value=>value?resolve(value):reject(Error('Falha ao exportar a vista 3D.')),'image/png'));if(closed)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`zero19-${design.model}-vista-3d.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Vista 3D exportada com créditos do modelo. Não use este PNG como filme DTF.')}catch(error){status(error.message,true)}finally{if(presentation)presentation.width=presentation.height=1;if(!closed){renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);render()}if(button.isConnected)button.disabled=false}
    };
    await loadModel(design.model);
  }catch(error){if(error.name!=='AbortError'&&!closed){find('.g3-loading').hidden=false;find('.g3-loading').textContent='Visualização 3D indisponível';status(error.message||'Use as vistas 2D; sua montagem foi preservada.',true)}}
  return controller;
}
