import {buildFinanceRecord,financeSummary,createProductionFinanceStore} from './production-finance-core.js?v=2.17.3';
const h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>value==null?'Não informado':Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const today=()=>{const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`};
export function createProductionFinanceUI(ctx){
  const account=ctx.owner(),store=createProductionFinanceStore(ctx),canView=()=>{try{return Boolean(account)&&ctx.owner()===account&&ctx.user()===account&&ctx.canView()===true}catch{return false}},guard=()=>{if(!canView())throw new Error('Financeiro de impressão exclusivo do titular da conta.');};
  function offerRecord({exportId,items,snapshot,companies=[]}){
    if(!canView())return;
    try{const frozen=JSON.stringify({items,snapshot,companies});if(new TextEncoder().encode(frozen).length>2*1024*1024)throw new Error('A cópia deste filme ultrapassa 2 MB.');({items,snapshot,companies}=JSON.parse(frozen))}catch(error){ctx.toast?.(error.message||'Não foi possível preservar uma cópia dos valores deste filme.','err');return}
    const estimate=snapshot?.estimate||null,estimated=estimate?.complete&&Number.isFinite(estimate.totals?.total)?estimate.totals.total:null,modal=document.createElement('div'),previous=document.activeElement,oldOverflow=document.body.style.overflow;let closed=false,busy=false;
    modal.className='modal-backdrop finance-record-backdrop';modal.innerHTML=`<section class="modal compact finance-record-modal" role="dialog" aria-modal="true" aria-label="Registrar custo desta impressão"><div class="modal-head"><div><div class="eyebrow">PRIVADO / FINANCEIRO DE IMPRESSÃO</div><h2>Registrar este custo?</h2></div><button class="btn ghost" data-close-finance aria-label="Fechar">×</button></div><p>Os PNGs foram preparados. Registrar é opcional e não confirma que a impressão aconteceu.</p><div class="finance-record-total"><small>${estimate?.complete?'Custo estimado deste filme':'Estimativa incompleta ou ainda não calculada'}</small><b>${money(estimated)}</b></div><p class="finance-muted">Tinta e pó são estimativas, não medições. O lançamento guarda os valores e hipóteses desta montagem; mudar os insumos depois não altera o histórico.</p><form><div class="field"><label>Data da impressão<input data-finance-date type="date" value="${today()}" required></label></div><div class="field"><label>Custo a registrar (R$)<input data-finance-cost inputmode="decimal" value="${estimated==null?'':h(estimated.toFixed(2))}" placeholder="Informe um valor confirmado" required></label></div><div class="field"><label>Receita atribuída somente a esta impressão (R$)<input data-finance-sale inputmode="decimal" placeholder="Opcional · não repetir o pedido inteiro"></label></div><div class="field"><label>Observação<textarea data-finance-notes rows="2" maxlength="2000" placeholder="Ex.: lote do pedido, previsão ou impressão realizada"></textarea></label></div><p class="finance-muted">Não puxamos o orçamento inteiro automaticamente: um pedido pode ter vários filmes. Sem receita informada, o lucro não será calculado. Nenhum valor é exibido para a equipe.</p><p data-finance-error class="cost-inline-error" role="alert"></p><div class="modal-footer"><button type="button" class="btn" data-close-finance>Agora não</button><button type="submit" class="btn primary">Registrar na conta</button></div></form></section>`;
    const close=(force=false)=>{if(closed||busy&&!force)return;closed=true;window.removeEventListener('z19:account-changing',onAccount);modal.remove();document.body.style.overflow=force?'':oldOverflow;if(!force&&previous?.isConnected)previous.focus()},onAccount=()=>close(true);window.addEventListener('z19:account-changing',onAccount);
    document.body.append(modal);document.body.style.overflow='hidden';modal.querySelectorAll('[data-close-finance]').forEach(button=>button.onclick=()=>close());modal.querySelector('[data-close-finance]').focus();modal.onkeydown=event=>{if(event.key==='Escape'){event.preventDefault();close()}if(event.key==='Tab'){const nodes=[...modal.querySelectorAll('button:not(:disabled),input,textarea')],first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};
    modal.querySelector('form').onsubmit=async event=>{event.preventDefault();if(busy||closed)return;busy=true;const button=event.submitter||modal.querySelector('button[type="submit"]');button.disabled=true;const error=modal.querySelector('[data-finance-error]');error.textContent='';try{guard();const cost=modal.querySelector('[data-finance-cost]').value,data=buildFinanceRecord({items,estimate,profileName:snapshot?.profileName||'',cost,sale:modal.querySelector('[data-finance-sale]').value,productionDate:modal.querySelector('[data-finance-date]').value,notes:modal.querySelector('[data-finance-notes]').value,companies,amountSource:estimated!=null&&Math.abs(Number(cost.replace(',','.'))-estimated)<.005?'estimate':'manual'});await store.save(exportId,data);guard();if(closed)return;busy=false;close();ctx.toast('Custo registrado no financeiro privado.','ok')}catch(failure){if(!closed)error.textContent=failure.message}finally{busy=false;if(button.isConnected)button.disabled=false}};
    return {close};
  }
  async function render(){
    guard();ctx.app.innerHTML=ctx.shell(`<main class="container production-finance"><section class="simple-hero"><div><div class="eyebrow">PRIVADO / SOMENTE TITULAR</div><h1>Financeiro de impressão</h1><p>Custos registrados após exportar seus filmes. Estimativas não são consumo medido.</p></div><button class="btn" data-finance-refresh>Atualizar</button></section><div class="finance-filters"><label>De<input type="date" data-finance-from></label><label>Até<input type="date" data-finance-to></label><label>Empresa<select data-finance-company><option value="all">Todas as empresas</option></select></label></div><div class="finance-content" aria-live="polite">Consultando lançamentos privados…</div><p class="finance-muted">Filmes com artes de várias empresas usam rateio explícito por área retangular × quantidade. O filtro de empresa mostra esse rateio, não um consumo medido separado. Comissão e receita do pedido não são repetidas automaticamente. A contribuição exibida é receita registrada menos custo registrado, não lucro líquido contábil.</p></main>`,{back:true});ctx.bindCommon();const root=ctx.app.querySelector('.production-finance'),content=root.querySelector('.finance-content');let records=[],loadSerial=0;
    const accountChanged=()=>{loadSerial++;records=[];root.replaceChildren();detach()},watcher=new MutationObserver(()=>{if(!root.isConnected)detach()}),detach=()=>{window.removeEventListener('z19:account-changing',accountChanged);watcher.disconnect()};window.addEventListener('z19:account-changing',accountChanged);watcher.observe(ctx.app,{childList:true,subtree:true});
    const draw=()=>{if(!root.isConnected)return;if(!canView()){root.replaceChildren();return}try{const summary=financeSummary(records,{from:root.querySelector('[data-finance-from]').value,to:root.querySelector('[data-finance-to]').value,workspaceId:root.querySelector('[data-finance-company]').value});content.innerHTML=`<div class="finance-totals"><article><small>Custo registrado</small><b>${money(summary.cost)}</b></article><article><small>Receita informada${summary.completeRevenue?'':' · parcial'}</small><b>${money(summary.knownSale)}</b></article><article><small>Contribuição estimada</small><b>${summary.completeRevenue?money(summary.contribution):'Receitas pendentes'}</b></article></div><div class="finance-records">${summary.records.map(record=>`<article><div><small>${h(record.data.productionDate.split('-').reverse().join('/'))} · ${h(record.data.profileName||'Impressão')}</small><h3>${record.data.items.reduce((sum,item)=>sum+item.quantity,0)} cópias · ${record.data.items.length} modelo(s) de arte</h3><p>${record.data.allocations.map(part=>h(part.name)).join(' · ')}</p>${record.data.notes?`<p>${h(record.data.notes)}</p>`:''}<details><summary>Artes e hipóteses do lançamento</summary>${record.data.items.map(item=>`<p>${h(item.name)} · ${item.quantity} × ${item.widthCm} × ${item.heightCm} cm</p>`).join('')}<small>${h((record.data.estimate?.assumptions||[]).join(' '))}</small></details></div><div class="finance-record-values"><b>${money(record.shownCost)}</b><small>${record.data.amountSource==='manual'?'Valor informado manualmente':'Estimativa do simulador'}</small><span>Receita: ${money(record.shownSale)}</span></div></article>`).join('')||'<div class="empty">Nenhum lançamento neste período. Ao preparar o PNG no Montar filme, escolha registrar o custo.</div>'}</div>`}catch(error){content.textContent=error.message}};
    const load=async()=>{const serial=++loadSerial,select=root.querySelector('[data-finance-company]'),selected=select.value,button=root.querySelector('[data-finance-refresh]');button.disabled=true;try{const loaded=await store.list();guard();if(!root.isConnected||serial!==loadSerial)return;records=loaded;const companies=new Map();for(const record of records)for(const part of record.data.allocations)companies.set(part.workspaceId||'',part.name);root.querySelector('[data-finance-company]').innerHTML='<option value="all">Todas as empresas</option>'+[...companies].map(([id,name])=>`<option value="${h(id)}">${h(name)}</option>`).join('');if([...select.options].some(option=>option.value===selected))select.value=selected;draw()}catch(error){if(root.isConnected&&serial===loadSerial&&canView()){records=[];content.innerHTML=`<div class="finance-unavailable"><h2>Histórico indisponível</h2><p>${h(error.message)}</p><p>Nenhum resultado foi tratado como zero. As tabelas e permissões privadas precisam estar habilitadas antes de registrar na nuvem.</p></div>`}}finally{if(root.isConnected&&serial===loadSerial)button.disabled=false}};
    root.querySelectorAll('.finance-filters input,.finance-filters select').forEach(input=>input.onchange=draw);root.querySelector('[data-finance-refresh]').onclick=load;await load();
  }
  return {render,offerRecord};
}
