import {QUEUE_STAGES} from './queue-core.js?v=2.17.3';

// Deterministic local guidance, not a language model. Never writes or advances status.
export const PROJECT_ADVISOR_VERSION=1;
const extensions=new Map(),has=(object,key)=>Object.prototype.hasOwnProperty.call(object||{},key);
const list=value=>Array.isArray(value)?JSON.parse(JSON.stringify(value)):[];
const positive=value=>value!==null&&value!==''&&Number.isFinite(Number(value))&&Number(value)>0;
const stamp=value=>{const result=Date.parse(value||'');return Number.isFinite(result)?result:null};
const dateOnly=value=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value||'')))return null;const date=new Date(value+'T12:00:00Z');return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===value?value:null};
const rank={critical:0,warning:1,info:2};
const priorities={PROJECT_SCOPE_MISMATCH:100,DELIVERY_OVERDUE:99,STATUS_MISMATCH:95,PAYMENT_PENDING:90,QUOTE_MISSING:89,DELIVERY_QUOTE_MISMATCH:88,DELIVERY_MISSING:85,DELIVERY_SOON:84,RETURN_DUE:83,ART_FILE_MISSING:80,ART_DIMENSIONS_MISSING:79,PRINT_READINESS_PENDING:78,ARTWORK_MISSING:77};
const evidence=(source,row,field)=>({source,id:row?.id||row?.asset_id||null,field,value:row?.[field]??null});
const latest=(a,b)=>(Number(b.sequence_no)||0)-(Number(a.sequence_no)||0)||(stamp(b.started_at||b.created_at)||0)-(stamp(a.started_at||a.created_at)||0)||String(b.id||'').localeCompare(String(a.id||''));
const documentOrder=(a,b)=>(Number(b.document_version)||0)-(Number(a.document_version)||0)||(stamp(b.generated_at)||0)-(stamp(a.generated_at)||0);
const html=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

/** Register a reviewed, synchronous rule alongside future application features. */
export function registerProjectAdvisorRule(rule){
  if(!rule||!/^[-a-z0-9_]{1,80}$/i.test(rule.id)||typeof rule.run!=='function'||!Array.isArray(rule.requires||[]))throw new Error('Regra do orientador inválida.');
  if(extensions.has(rule.id))throw new Error('Já existe uma regra com este identificador.');extensions.set(rule.id,{...rule,requires:[...(rule.requires||[])]});return ()=>extensions.delete(rule.id);
}
export function evaluateProjectAdvice(input={}){
  const incomplete=new Set(),known={},workspace=input.workspace?JSON.parse(JSON.stringify(input.workspace)):null;
  const names=['projects','statuses','quotes','quoteItems','assets','printProfiles','folders','documents','teamProfiles'];
  const data={};for(const name of names){known[name]=input.known?.[name]!==false&&Array.isArray(input[name]);data[name]=list(input[name]);}
  const result={version:1,workspaceId:workspace?.id||null,projectId:null,stage:null,closed:false,applicable:true,issues:[],summary:'Dados insuficientes para orientar este projeto.',nextAction:null,incomplete:[],confidence:'partial',counts:{quotes:0,paidQuotes:0,arts:0,readyArts:0},queuePosition:null};
  if(!workspace?.id){result.incomplete=['workspace'];return result}
  if(workspace.workspace_type&&workspace.workspace_type!=='client')return {...result,applicable:false,summary:'Este orientador acompanha projetos de clientes.',confidence:'complete'};
  const own=row=>!workspace.owner_id||!row.owner_id||row.owner_id===workspace.owner_id;
  const projects=data.projects.filter(row=>row.workspace_id===workspace.id&&own(row)).sort(latest);
  const supplied=has(input,'project'),project=supplied&&input.project?JSON.parse(JSON.stringify(input.project)):supplied?null:projects[0]||null;
  const projectKnown=input.known?.projects!==false&&(supplied||known.projects);
  const action=(type,label,details={})=>({type,label,target:type==='open_film'?'/filme':type==='open_queue'?`/fila/${details.stage}`:`/ambiente/${encodeURIComponent(workspace.id)}`,workspaceId:workspace.id,projectId:project?.id||null,...details});
  const add=(code,severity,title,detail,facts,recommendedAction)=>{if(!result.issues.some(issue=>issue.code===code))result.issues.push({code,severity,title,detail,evidence:facts,recommendedAction,confidence:'verified',priority:priorities[code]??50})};
  if(project&&((project.workspace_id&&project.workspace_id!==workspace.id)||!own(project))){add('PROJECT_SCOPE_MISMATCH','critical','Projeto fora desta empresa','O projeto recebido não pertence a esta empresa. Reabra o ambiente antes de continuar.',[evidence('project',project,'workspace_id')],action('open_workspace','Reabrir empresa'));incomplete.add('projectScope');return finish()}
  result.projectId=project?.id||null;
  if(!project){if(projectKnown)add('PROJECT_MISSING','warning','Crie o primeiro projeto','Esta empresa ainda não possui um projeto para separar orçamento, artes e andamento.',[evidence('workspace',workspace,'id')],action('new_project','Criar projeto'));else incomplete.add('projects');return finish()}
  const scoped=row=>row.project_id===project.id&&(!row.workspace_id||row.workspace_id===workspace.id)&&own(row);
  const quotes=data.quotes.filter(scoped),assets=data.assets.filter(scoped),arts=assets.filter(row=>row.asset_type==='arte'),folders=data.folders.filter(scoped);
  const quoteIds=new Set(quotes.map(row=>row.id)),assetIds=new Set(arts.map(row=>row.id));
  const printProfiles=data.printProfiles.filter(row=>assetIds.has(row.asset_id)&&(!row.project_id||row.project_id===project.id)&&own(row)),profiles=new Map(printProfiles.map(row=>[row.asset_id,row]));
  const documents=data.documents.filter(row=>quoteIds.has(row.quote_id)&&(!row.project_id||row.project_id===project.id)&&own(row));
  const status=known.statuses?data.statuses.find(row=>row.id===project.status_id&&own(row)):null,workspaceStatus=known.statuses?data.statuses.find(row=>row.id===workspace.status_id&&own(row)):null;
  const stage=status&&has(status,'queue_stage')?status.queue_stage:null,operational=QUEUE_STAGES.includes(stage),paid=quotes.filter(row=>row.payment_status==='paid');result.stage=stage;
  result.closed=Boolean(project.finalized_at||project.desisted_at||status?.is_finalized);
  if(result.closed){if(project.finalized_at&&project.desisted_at)add('CLOSED_STATE_CONFLICT','warning','Confira o encerramento','O mesmo projeto registra finalização e desistência. Revise o histórico sem criar uma nova produção.',[evidence('project',project,'finalized_at'),evidence('project',project,'desisted_at')],action('view_history','Ver histórico'));result.summary=project.desisted_at?'Projeto encerrado por desistência.':'Projeto finalizado; histórico preservado.';result.nextAction=action('view_history','Ver histórico');result.confidence='complete';return finish()}
  for(const name of ['statuses','quotes','assets','printProfiles'])if(!known[name])incomplete.add(name);
  if(quotes.length){for(const name of ['quoteItems','documents'])if(!known[name])incomplete.add(name)}
  if(arts.some(asset=>asset.folder_id)&&!known.folders)incomplete.add('folders');
  if(has(project,'status_id')&&known.statuses&&!status)add('STATUS_MISSING','warning','Defina o status do projeto','Não há um status válido associado ao projeto atual.',[evidence('project',project,'status_id')],action('review_status','Revisar status'));
  if(status&&stage===null)incomplete.add('statuses.queue_stage');
  if(status?.active===false)add('STATUS_INACTIVE','warning','Status desativado','O projeto continua associado a um status que foi desativado.',[evidence('status',status,'active')],action('review_status','Escolher status ativo'));
  if(status&&workspaceStatus&&status.id!==workspaceStatus.id)add('STATUS_MISMATCH',workspaceStatus.is_finalized?'critical':'warning','Empresa e projeto em etapas diferentes','As filas usam o status do projeto atual. Revise o andamento para manter o card e a produção coerentes.',[evidence('project',project,'status_id'),evidence('workspace',workspace,'status_id')],action('review_status','Conferir andamento'));
  if(!has(project,'status_id'))incomplete.add('project.status_id');

  const responsible=workspace.responsible_user_id||project.responsible_user_id;
  if(responsible&&!known.teamProfiles)incomplete.add('teamProfiles');
  if(!responsible){if(has(workspace,'responsible_user_id')&&has(project,'responsible_user_id'))add('RESPONSIBLE_MISSING','warning','Defina quem acompanha este pedido','Sem responsável, o projeto não aparece em “Meus” para um integrante da equipe.',[evidence('workspace',workspace,'responsible_user_id'),evidence('project',project,'responsible_user_id')],action('edit_workspace','Definir responsável'));else incomplete.add('responsible_user_id')}
  else if(known.teamProfiles){const member=data.teamProfiles.find(row=>row.id===responsible&&(!row.account_owner_id||!workspace.owner_id||row.account_owner_id===workspace.owner_id));if(!member||member.active===false)add('RESPONSIBLE_UNAVAILABLE','warning','Confira o responsável','O responsável não aparece na equipe ativa carregada. Confirme quem seguirá com o pedido.',[evidence('workspace',workspace,'responsible_user_id'),...(member?[evidence('profile',member,'active')]:[])],action('edit_workspace','Revisar responsável'))}

  let today=dateOnly(input.today);const now=input.now instanceof Date?input.now:new Date(input.now??Date.now());
  if(!today&&Number.isFinite(now.getTime())){try{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:input.timeZone||'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now),part=type=>parts.find(p=>p.type===type).value;today=`${part('year')}-${part('month')}-${part('day')}`}catch{incomplete.add('currentDate')}}
  const delivery=dateOnly(project.delivery_date);
  if(!has(project,'delivery_date'))incomplete.add('project.delivery_date');
  else if(project.delivery_date&&!delivery)add('DELIVERY_INVALID','warning','Data de entrega inválida','A data registrada não é um dia válido. Confira o calendário do pedido.',[evidence('project',project,'delivery_date')],action('set_delivery','Corrigir entrega'));
  else if(!delivery&&(operational||paid.length))add('DELIVERY_MISSING',operational?'critical':'warning','Defina a data de entrega','A fila operacional exige a data do projeto, além de um orçamento pago.',[evidence('project',project,'delivery_date')],action('set_delivery','Escolher entrega'));
  const differentQuoteDates=delivery?paid.filter(quote=>dateOnly(quote.delivery_date)&&quote.delivery_date!==delivery):[];
  if(known.quotes&&differentQuoteDates.length)add('DELIVERY_QUOTE_MISMATCH','warning','Projeto e orçamento com prazos diferentes','A data usada na fila difere da registrada em orçamento pago. Confira o prazo combinado antes de enviar o PDF ao cliente. Gerar um PDF não altera automaticamente essas datas nem o pagamento.',[evidence('project',project,'delivery_date'),...differentQuoteDates.map(quote=>evidence('quote',quote,'delivery_date'))],action('open_quote_pdf','Revisar orçamento e prazo',{quoteId:differentQuoteDates[0].id}));
  if(delivery&&today){const delta=Math.round((Date.parse(delivery+'T12:00:00Z')-Date.parse(today+'T12:00:00Z'))/86400000);if(delta<0)add('DELIVERY_OVERDUE','critical',`Entrega vencida há ${-delta} dia(s)`,'O projeto ainda está aberto e a data combinada já passou. Confira a produção e combine o próximo passo com o cliente.',[evidence('project',project,'delivery_date')],action('open_workspace','Revisar pedido atrasado'));else if(delta<=1)add('DELIVERY_SOON','warning',delta===0?'Entrega prevista para hoje':'Entrega prevista para amanhã','Confira as artes, a fila e o andamento antes do prazo.',[evidence('project',project,'delivery_date')],action('open_workspace','Conferir entrega'))}
  const reminder=stamp(project.reminder_at);if(reminder!==null&&Number.isFinite(now.getTime())&&reminder<=now.getTime())add('RETURN_DUE','warning','Retorno programado chegou','Este projeto possui um retorno agendado já vencido. Confira se o atendimento foi realizado.',[evidence('project',project,'reminder_at')],action('open_workspace','Retomar atendimento'));

  const paymentKnown=known.quotes&&quotes.every(quote=>['paid','unpaid','pending'].includes(quote.payment_status));
  if(known.quotes){if(!quotes.length)add('QUOTE_MISSING',operational?'critical':'warning','Monte o orçamento deste projeto','Nenhum orçamento foi encontrado vinculado ao projeto atual. Orçamentos de projetos anteriores não liberam esta produção.',[evidence('project',project,'id')],action('new_quote','Criar orçamento'));
    else if(!paymentKnown)incomplete.add('quotes.payment_status');
    else if(!paid.length)add('PAYMENT_PENDING',operational?'critical':'warning',operational?'Produção sem pagamento confirmado':'Pagamento ainda não confirmado','Nenhum orçamento do projeto está marcado como pago. Confira o recebimento; esta orientação não marca pagamentos automaticamente.',quotes.map(quote=>evidence('quote',quote,'payment_status')),action('review_payment','Conferir pagamento',{quoteId:quotes[0].id}));
    else if(quotes.some(quote=>quote.payment_status!=='paid'))add('ADDITIONAL_QUOTE_PENDING','info','Há outro orçamento pendente','Existe orçamento pago que atende à regra da fila, mas também há orçamento pendente no mesmo projeto. Confirme quais itens fazem parte desta produção.',quotes.filter(quote=>quote.payment_status!=='paid').map(quote=>evidence('quote',quote,'payment_status')),action('review_payment','Conferir os orçamentos'));
    const legacy=data.quotes.filter(quote=>quote.workspace_id===workspace.id&&!quote.project_id&&own(quote));if(!quotes.length&&legacy.length)add('UNLINKED_QUOTES','warning','Orçamento sem projeto vinculado','Há orçamento da empresa sem vínculo de projeto. Confira o histórico e o vínculo; não o considere automaticamente como pagamento deste pedido.',legacy.map(quote=>evidence('quote',quote,'project_id')),action('open_workspace','Conferir vínculo do orçamento'));
  }
  if(known.quoteItems){for(const quote of quotes){const rows=data.quoteItems.filter(row=>row.quote_id===quote.id&&own(row));if(!rows.length)add('QUOTE_EMPTY','warning','Orçamento sem produtos','Há um orçamento do projeto sem itens cadastrados. Revise antes de enviar ao cliente.',[evidence('quote',quote,'id')],action('new_quote','Revisar orçamento',{quoteId:quote.id}));else if(rows.some(row=>!positive(row.quantity)))add('QUOTE_QUANTITY_INVALID','warning','Quantidade inválida no orçamento','Um item tem quantidade nula, zero ou inválida. Revise o orçamento antes de produzir.',rows.filter(row=>!positive(row.quantity)).map(row=>evidence('quote_item',row,'quantity')),action('open_workspace','Revisar quantidades',{quoteId:quote.id}))}}
  if(known.documents&&known.quotes){for(const quote of quotes){const doc=documents.filter(row=>row.quote_id===quote.id).sort(documentOrder)[0];if(!doc)add('QUOTE_PDF_MISSING','info','Gere o PDF atualizado','O orçamento já existe, mas ainda não tem PDF registrado para compartilhar.',[evidence('quote',quote,'id')],action('open_quote_pdf','Gerar PDF',{quoteId:quote.id}));else if(doc.stale===true||stamp(quote.updated_at)!==null&&stamp(doc.quote_updated_at)!==null&&stamp(quote.updated_at)>stamp(doc.quote_updated_at))add('QUOTE_PDF_STALE','warning','O PDF está desatualizado','O orçamento mudou depois da versão registrada. Gere o PDF novamente antes de compartilhar.',[evidence('document',doc,'stale'),evidence('document',doc,'quote_updated_at'),evidence('quote',quote,'updated_at')],action('open_quote_pdf','Atualizar PDF',{quoteId:quote.id}))}}

  const inReadyFolder=asset=>{const seen=new Set();let id=asset.folder_id;while(id&&!seen.has(id)){seen.add(id);const folder=folders.find(row=>row.id===id);if(!folder)return false;if(folder.purpose==='artes_prontas')return true;id=folder.parent_id}return false};
  const dimensions=profile=>positive(profile?.default_width_cm)&&positive(profile?.default_height_cm),ready=arts.filter(asset=>profiles.get(asset.id)?.ready_for_print===true&&dimensions(profiles.get(asset.id))&&(asset.processed_path||asset.original_path));
  if(known.assets&&assets.some(asset=>!has(asset,'asset_type')))incomplete.add('assets.asset_type');
  else if(known.assets&&!arts.length&&(operational||paid.length))add('ARTWORK_MISSING',stage==='ready_production'||stage==='production'?'critical':'warning','Adicione as artes deste projeto','O pedido tem atividade de produção, mas não há artes vinculadas ao projeto atual.',[evidence('project',project,'id')],action('upload_art','Adicionar arte'));
  if(known.assets&&known.printProfiles){
    const intended=arts.filter(asset=>profiles.get(asset.id)?.ready_for_print===true||asset.metadata?.print_ready_intent===true||known.folders&&inReadyFolder(asset));
    const dimensionsKnown=asset=>!profiles.has(asset.id)||has(profiles.get(asset.id),'default_width_cm')&&has(profiles.get(asset.id),'default_height_cm');
    const fileKnown=asset=>Boolean(asset.processed_path||asset.original_path)||has(asset,'processed_path')&&has(asset,'original_path');
    if(intended.some(asset=>!dimensionsKnown(asset)))incomplete.add('printProfiles.dimensions');
    if(intended.some(asset=>!fileKnown(asset)))incomplete.add('assets.file_path');
    const withoutSize=intended.filter(asset=>dimensionsKnown(asset)&&!dimensions(profiles.get(asset.id)));
    if(withoutSize.length)add('ART_DIMENSIONS_MISSING','critical',`${withoutSize.length} arte(s) pronta(s) sem medida válida`,'Para entrar no filme, a arte precisa de largura e altura positivas em centímetros. Confira cada tamanho no cadastro.',withoutSize.map(asset=>({source:'asset',id:asset.id,field:'print_dimensions',value:{widthCm:profiles.get(asset.id)?.default_width_cm??null,heightCm:profiles.get(asset.id)?.default_height_cm??null}})),action('edit_print_profile','Definir medida',{assetId:withoutSize[0].id}));
    const missingFile=intended.filter(asset=>has(asset,'processed_path')&&has(asset,'original_path')&&!asset.processed_path&&!asset.original_path);if(missingFile.length)add('ART_FILE_MISSING','critical','Arte liberada sem arquivo','Há arte marcada para impressão sem caminho de arquivo disponível. Confira o cadastro antes de montar o filme.',missingFile.map(asset=>evidence('asset',asset,'id')),action('edit_print_profile','Revisar arte',{assetId:missingFile[0].id}));
    const halftones=arts.filter(asset=>{const p=profiles.get(asset.id);return p?.ready_for_print&&p.halftone===true&&p.allow_internal_nesting===true});if(halftones.length)add('HALFTONE_NESTING_REVIEW','warning','Revise o encaixe de arte halftone','Há perfil halftone com encaixe interno ligado. O cálculo deve preservar a área retangular, sem encaixar outra arte nos pontos transparentes.',halftones.map(asset=>evidence('print_profile',profiles.get(asset.id),'allow_internal_nesting')),action('edit_print_profile','Revisar halftone',{assetId:halftones[0].id}));
    const mismatch=arts.filter(asset=>{const p=profiles.get(asset.id);return p?.ready_for_print&&dimensions(p)&&positive(p.aspect_ratio)&&Math.abs(Number(p.default_width_cm)/Number(p.default_height_cm)/Number(p.aspect_ratio)-1)>.01});if(mismatch.length)add('ART_PROPORTION_MISMATCH','warning','Medidas e proporção divergentes','A proporção cadastrada difere da relação entre largura e altura em mais de 1%. Confira para não esticar a arte.',mismatch.map(asset=>evidence('print_profile',profiles.get(asset.id),'aspect_ratio')),action('edit_print_profile','Conferir proporção',{assetId:mismatch[0].id}));
    const readinessKnown=arts.every(asset=>!profiles.has(asset.id)||has(profiles.get(asset.id),'ready_for_print')&&dimensionsKnown(asset)&&fileKnown(asset));
    if(!readinessKnown)incomplete.add('printProfiles.readiness');
    if(readinessKnown&&arts.length&&!ready.length&&!withoutSize.length&&['ready_production','production'].includes(stage))add('PRINT_READINESS_PENDING','critical','Nenhuma arte liberada para o filme','Há artes no projeto, mas nenhuma combina liberação, medidas válidas e arquivo. Revise os perfis antes de imprimir.',arts.map(asset=>evidence('asset',asset,'id')),action('edit_print_profile','Revisar liberação',{assetId:arts[0].id}));
  }
  result.counts={quotes:quotes.length,paidQuotes:paid.length,arts:arts.length,readyArts:ready.length};
  if(input.queueSnapshot){if(input.queueSnapshot.error)incomplete.add('queueSnapshot');else{const row=(input.queueSnapshot.rows||[]).find(row=>row.project?.id===project.id&&row.workspace?.id===workspace.id);if(row){result.queuePosition=row.position??null;if(row.stage!==stage)add('QUEUE_STAGE_MISMATCH','warning','Atualize a leitura da fila','O projeto e o retrato carregado da fila mostram etapas diferentes. Atualize a consulta antes de decidir.',[{source:'queue',id:project.id,field:'stage',value:row.stage},evidence('status',status,'queue_stage')],action('open_queue','Reabrir fila',{stage:QUEUE_STAGES.includes(stage)?stage:row.stage}))}}}
  const context={workspace,project,status,stage,closed:result.closed,quotes,assets:arts,printProfiles,folders,documents,quoteItems:data.quoteItems.filter(row=>quoteIds.has(row.quote_id)&&own(row)),teamProfiles:data.teamProfiles.filter(own),known:{...known},today,counts:{...result.counts},action};
  for(const rule of extensions.values()){if(rule.requires.some(name=>!known[name])){incomplete.add('rule:'+rule.id);continue}try{const items=rule.run(context)||[];if(!Array.isArray(items))throw new Error('A regra precisa ser síncrona e retornar uma lista.');for(const issue of items){if(!issue||typeof issue.code!=='string'||!rank.hasOwnProperty(issue.severity)||!Array.isArray(issue.evidence)||!issue.evidence.length)throw new Error('Regra sem evidência válida.');add(issue.code,issue.severity,String(issue.title||''),String(issue.detail||''),issue.evidence,issue.recommendedAction||action('open_workspace','Revisar pedido'))}}catch{incomplete.add('rule:'+rule.id)}}
  const canGuide=known.statuses&&paymentKnown&&known.assets&&known.printProfiles&&has(project,'delivery_date')&&!['project.status_id','statuses.queue_stage','printProfiles.dimensions','printProfiles.readiness','assets.file_path','assets.asset_type'].some(field=>incomplete.has(field));
  if(canGuide&&paid.length&&delivery&&ready.length&&!result.issues.some(issue=>issue.severity==='critical')){result.nextAction=stage==='production'?action('review_status','Conferir estampa e entrega'):stage==='ready_production'?action('open_film','Montar filme'):action('review_status','Revisar liberação para produção',{stage:'ready_production'});result.summary=stage==='production'?'Pedido em produção: confira a estampa e a entrega.':stage==='ready_production'?'Pagamento, prazo e arte liberada conferidos. Monte o filme. Ao usar TIFF com Spot, confira o primeiro arquivo no RIP antes de produzir.':'Há arte liberada, pagamento e entrega. Revise a passagem para produção.'}
  return finish();

  function finish(){
    result.issues.sort((a,b)=>rank[a.severity]-rank[b.severity]||b.priority-a.priority||a.code.localeCompare(b.code));result.incomplete=[...incomplete];result.confidence=incomplete.size?'partial':'complete';
    if(result.issues.length){const priority=result.issues[0];result.summary=priority.title;result.nextAction=priority.recommendedAction}
    else if(!result.closed&&!result.nextAction)result.summary=incomplete.size?'Leitura parcial: abra o projeto para conferir os dados disponíveis.':'Nenhuma pendência detectada nos dados conferidos.';
    if(!result.nextAction)result.nextAction=action('open_workspace','Abrir projeto');return result;
  }
}

/** Optional markup only. The caller handles data-advisor-code using the returned action. */
export function renderProjectAdvice(advice,{compact=false}={}){
  if(!advice?.applicable)return '';
  const top=advice.issues[0],severity=top?.severity||'info',tag=advice.confidence==='partial'?'Leitura parcial':'Dados conferidos';
  if(compact)return `<div class="project-advice-badge ${html(severity)}"><span>${html(advice.summary)}</span><small>${html(tag)}</small></div>`;
  return `<section class="project-advisor" aria-label="Orientador do projeto"><header><div><span class="eyebrow">Próximo passo · orientador local</span><h2>${html(advice.summary)}</h2></div><span class="project-advice-confidence">${html(tag)}</span></header><p>Regras baseadas nos registros deste projeto. Nada é enviado a uma IA e nenhuma etapa é alterada automaticamente.</p>${advice.issues.length?`<div class="project-advice-list">${advice.issues.map(issue=>`<article class="${html(issue.severity)}"><b>${html(issue.title)}</b><p>${html(issue.detail)}</p><details><summary>Por que este aviso apareceu?</summary><ul>${issue.evidence.map(fact=>`<li>${html(fact.source)} · ${html(fact.field)}: ${html(typeof fact.value==='object'?JSON.stringify(fact.value):fact.value??'não informado')}</li>`).join('')}</ul></details><button class="btn small" type="button" data-advisor-code="${html(issue.code)}">${html(issue.recommendedAction?.label||'Revisar')}</button></article>`).join('')}</div>`:`<button class="btn primary" data-advisor-code="next">${html(advice.nextAction?.label||'Abrir projeto')}</button>`}${advice.incomplete.length?'<small class="project-advice-incomplete">Algumas verificações dependem de dados ainda não carregados. Ausência de aviso não confirma que tudo está pronto.</small>':''}</section>`;
}
