import {garmentFrame,SIDE_LABELS} from './garment-scene.js?v=2.17.3';
const h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function renderStudioHome(ctx){
  ctx.app.innerHTML=ctx.shell(`<main class="container studio-home"><section class="studio-home-hero"><div class="studio-home-copy"><div class="eyebrow">ZERO 19 / ESTÚDIO DE MOCKUPS</div><h1>Comece pela peça.<br><span>Crie de todos os lados.</span></h1><p>Monte sua camiseta do zero: escolha o modelo, adicione artes e ajuste cada posição em centímetros.</p><div class="studio-home-actions"><button class="btn primary" data-new-garment>＋ Nova montagem</button><button class="btn" data-nav="/biblioteca/artes">Escolher pelas artes</button></div><div class="studio-home-chips"><span>Normal e oversized</span><span>3 cores</span><span>Frente, costas e mangas</span></div></div><div class="studio-home-showcase" aria-hidden="true"><div class="studio-home-shirt"></div><span>Seu espaço para criar</span></div></section><section class="studio-home-capabilities" aria-label="Recursos do estúdio"><article><span>01</span><div><b>Vista por vista</b><p>Adicione várias artes, ajuste medidas e fixe cada posição.</p></div></article><article><span>02</span><div><b>Apresente ao cliente</b><p>Baixe a imagem da peça, a ficha com medidas ou o modelo liso.</p></div></article><article><span>03</span><div><b>Continue em qualquer aparelho</b><p>Salve a montagem na sua conta e reabra no computador ou celular.</p></div></article></section><section class="studio-home-saved"><div class="section-title-row"><div><div class="eyebrow">CONTINUE DE ONDE PAROU</div><h2>Suas montagens</h2><p>Salvas na conta. Rascunhos antigos deste aparelho aparecem identificados para transferência segura.</p></div><button class="btn" data-refresh-garments>Atualizar lista</button></div><div class="studio-home-drafts" aria-live="polite"></div></section><p class="studio-home-availability">Monte com vistas fotográficas e abra “Ver em 3D” para girar a peça real. O corte normal 3D é uma adaptação identificada da malha oversized, não uma digitalização independente. Links para o cliente exigem o sistema publicado; no localhost, baixe as imagens ou a apresentação 2D.</p></main>`,{back:true});
  ctx.bindCommon();const root=ctx.app.querySelector('.studio-home'),list=root.querySelector('.studio-home-drafts');
  const open=async draftId=>{try{await ctx.artStudio.openGarment(null,{...(draftId?{draftId}:{}),onSaved:()=>{if(root.isConnected)draw()}})}catch(error){ctx.toast(error.message||'Não foi possível abrir a montagem.','err')}};
  let generation=0;
  const draw=async()=>{
    const ticket=++generation;list.innerHTML='<div class="studio-home-empty">Carregando montagens da conta…</div>';
    try{
      const result=await ctx.artStudio.listGarmentDrafts();if(ticket!==generation||!root.isConnected)return;const records=result.records;
      const warning=result.warning?`<div class="studio-home-empty"><b>${result.cloudAvailable?'Atenção aos rascunhos antigos':'Nuvem indisponível neste momento'}</b><p>${h(result.warning)}</p><p>Nenhum rascunho antigo foi apagado. Atualize a lista para tentar novamente.</p></div>`:'';
      list.innerHTML=records.length?records.map(record=>{
        const scene=record.scene,side=scene.layers[0]?.side||'front',frame=garmentFrame(scene,side),color={black:'Preta',white:'Branca',offwhite:'Off-white'}[scene.color];
        const layers=scene.layers.filter(layer=>layer.side===side).map(layer=>`<img src="${h(ctx.publicUrl(layer.path))}" alt="" loading="lazy" style="left:${(frame.left+layer.x/frame.widthCm*frame.fraction)*100}%;top:${(frame.top+layer.y/frame.lengthCm*frame.heightFraction)*100}%;width:${layer.width/frame.widthCm*frame.fraction*100}%;height:${layer.width/layer.ratio/frame.lengthCm*frame.heightFraction*100}%">`).join('');
        return `<article class="studio-draft-card"><button class="studio-draft-preview" data-open-draft="${h(record.id)}" aria-label="Abrir ${h(record.title)}" style="aspect-ratio:1 / ${frame.ratio};background-image:url('${h(frame.path)}');background-position:${frame.column*100}% ${frame.row*100}%">${layers}</button><div class="studio-draft-body"><span class="studio-draft-local">${record.storage==='cloud'?'Salva na nuvem':'Rascunho antigo · transferir à nuvem'}</span><h3>${h(record.title)}</h3><p>${scene.model==='oversized'?'Oversized':'Normal'} · ${h(color)} · ${scene.layers.length} estampa(s)</p><div class="studio-draft-faces">${[...new Set(scene.layers.map(layer=>layer.side))].map(view=>`<span>${h(SIDE_LABELS[view])}</span>`).join('')||'<span>Camiseta lisa</span>'}</div><small>Salva em ${h(new Date(record.updatedAt).toLocaleString('pt-BR'))}</small><button class="btn primary" data-open-draft="${h(record.id)}">Continuar montagem</button></div></article>`;
      }).join(''):'<div class="studio-home-empty"><b>Sua próxima camiseta começa aqui.</b><p>Abra uma montagem vazia e escolha as artes dentro do estúdio.</p><button class="btn primary" data-new-garment>Montar primeira camiseta</button></div>';
      list.insertAdjacentHTML('afterbegin',warning);
    }catch(error){if(ticket!==generation||!root.isConnected)return;list.innerHTML=`<div class="studio-home-empty"><b>Não foi possível ler as montagens.</b><p>${h(error.message)}</p><p>Nenhum rascunho foi apagado.</p></div>`}
    list.querySelectorAll('[data-open-draft]').forEach(button=>button.onclick=()=>open(button.dataset.openDraft));list.querySelector('[data-new-garment]')?.addEventListener('click',()=>open());
  };
  root.querySelector('[data-new-garment]').onclick=()=>open();root.querySelector('[data-refresh-garments]').onclick=draw;draw();
}
