import assert from 'node:assert/strict';
import {baseCharacter,opticalOffset} from '../lettering-layout-v2176.js';
import {createSavedFilmDrafts,checkedNamedDraft,filmNameProof,NAMED_FILM_DRAFT_KIND} from '../film-saved-drafts.js';
assert.equal(baseCharacter('Ç'),'C');assert.equal(baseCharacter('Á'),'A');assert.equal(baseCharacter('Ã'),'A');
const r=new Float64Array([8,7,6,5]),l=new Float64Array([4,3,2,1]);
const offset=opticalOffset(r,l,1);assert.ok(offset<9&&offset>=5,'A/V corners close without contact');
const names=[{localId:'a',type:'team_customization',name:'CÉSAR',number:'',compositionGroupId:'g',quantity:1},{localId:'b',type:'team_customization',name:'',number:'1',compositionGroupId:'g',quantity:1},{localId:'c',type:'team_customization',name:'',number:'0',compositionGroupId:'g',quantity:1},{localId:'d',type:'team_customization',name:'RODA',compositionGroupId:'x',quantity:1}];
assert.deepEqual(filmNameProof(names).map(x=>[x.name,x.number]),[['CÉSAR','10'],['RODA','']]);
assert.equal(names[0].name,'CÉSAR');
const items=[{localId:'n',type:'team_customization',sourceId:'set',quantity:1,name:'CÉSAR',number:'',widthCm:15,heightCm:6.5,nameHeightCm:5.5,letteringMetricsVersion:2,rotationPolicy:'90',previewDataUrl:'transient'}];
const data={items,settings:{mediaId:'film',mode:'maximum',gapMm:3,freeRotation:false,angleStep:30},layout:null};
assert.equal(checkedNamedDraft(data,'owner').data.items[0].previewDataUrl,undefined);
assert.equal(items[0].previewDataUrl,'transient');
assert.throws(()=>checkedNamedDraft({...data,items:[{...items[0],heightCm:0}]},'owner'));
const db=new Map();let actor='user',fail=false;
const supabase={from(table){assert.equal(table,'z19p_print_jobs');const filters=[];let insert=null,limit=null;
  const q={select(){return q},eq(k,v){filters.push([k,v]);return q},order(){return q},range(a,b){limit=[a,b];return q},insert(value){insert=JSON.parse(JSON.stringify(value));return q},single(){return q},then(resolve,reject){return Promise.resolve().then(()=>{if(fail)return {error:{message:'offline'}};if(insert){db.set(insert.id,{...insert,updated_at:'2026-09-18T20:00:00Z'});return {data:{id:insert.id,name:insert.name}};}let rows=[...db.values()].filter(row=>filters.every(([k,v])=>(k==='settings_snapshot->>kind'?row.settings_snapshot.kind:row[k])===v));if(limit)return {data:rows.slice(limit[0],limit[1]+1)};return {data:rows[0]||null};}).then(resolve,reject)}};return q;}};
const store=createSavedFilmDrafts({supabase,owner:()=> 'owner',user:()=>actor});
const a=await store.save(data,'Time maior',58,'film');const b=await store.save({...data,items:[{...items[0],name:'DAVID'}]},'Pedido pequeno',28,'film');
assert.notEqual(a.id,b.id);assert.equal(db.size,2);assert.equal((await store.list()).rows.length,2);
const restored=await store.load(a.id);assert.equal(restored.data.items[0].name,'CÉSAR');assert.equal(restored.data.items[0].nameHeightCm,5.5);assert.equal(restored.data.layout,null);
restored.data.items[0].name='EDITADO';assert.equal((await store.load(a.id)).data.items[0].name,'CÉSAR','loading never edits the saved snapshot');
fail=true;await assert.rejects(store.save(data,'Falhou',58));assert.equal(db.size,2);assert.equal(items[0].name,'CÉSAR');fail=false;
actor='other';await assert.rejects(store.load(a.id),/conta/);actor='user';
assert.ok([...db.values()].every(v=>v.settings_snapshot.kind===NAMED_FILM_DRAFT_KIND));
console.log('v2.17.6: accent bases, optical clearance, exact name proof, two independent drafts, recover/edit isolation, offline preservation and account guards passed.');
