-- v2.13 — rateio de comissão e resumo individual seguro.
begin;
create table if not exists public.z19p_commission_shares(id uuid primary key default gen_random_uuid(),owner_id uuid not null default public.z19p_current_account_owner(),commission_id uuid not null references public.z19p_commissions(id) on delete cascade,recipient_user_id uuid not null references public.z19p_profiles(id) on delete restrict,share_percent numeric(7,4) not null check(share_percent>0 and share_percent<=100),share_amount numeric(12,2) not null default 0 check(share_amount>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(commission_id,recipient_user_id));
alter table public.z19p_commission_shares enable row level security;
drop policy if exists z19p_commission_shares_select on public.z19p_commission_shares;create policy z19p_commission_shares_select on public.z19p_commission_shares for select to authenticated using(owner_id=public.z19p_current_account_owner() and(public.z19p_is_admin() or recipient_user_id=auth.uid()));
drop policy if exists z19p_commission_shares_admin_write on public.z19p_commission_shares;create policy z19p_commission_shares_admin_write on public.z19p_commission_shares for all to authenticated using(public.z19p_is_admin() and owner_id=public.z19p_current_account_owner()) with check(public.z19p_is_admin() and owner_id=public.z19p_current_account_owner());
create index if not exists z19p_commission_shares_recipient_idx on public.z19p_commission_shares(owner_id,recipient_user_id,commission_id);
create or replace function public.z19p_set_commission_split(p_commission_id uuid,p_shares jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_owner uuid:=public.z19p_current_account_owner();v_comm public.z19p_commissions%rowtype;v_row jsonb;v_uid uuid;v_pct numeric;v_sum numeric:=0;v_count int:=0;v_i int:=0;v_assigned numeric:=0;v_amount numeric;
begin if not public.z19p_is_admin() then raise exception 'Apenas o administrador pode dividir comissões.';end if;select * into v_comm from public.z19p_commissions where id=p_commission_id and owner_id=v_owner for update;if not found then raise exception 'Comissão não encontrada.';end if;if v_comm.status not in('pending','approved')then raise exception 'Esta comissão não pode mais ser dividida.';end if;if p_shares is null or jsonb_typeof(p_shares)<>'array' then raise exception 'Divisão inválida.';end if;if jsonb_array_length(p_shares)=0 then delete from public.z19p_commission_shares where commission_id=v_comm.id and owner_id=v_owner;return jsonb_build_object('ok',true,'split',false,'commission_id',v_comm.id);end if;create temporary table if not exists pg_temp.z19p_split_input(user_id uuid primary key,pct numeric)on commit drop;truncate pg_temp.z19p_split_input;for v_row in select value from jsonb_array_elements(p_shares)loop begin v_uid:=(v_row->>'user_id')::uuid;exception when others then raise exception 'Usuário inválido na divisão.';end;begin v_pct:=replace(coalesce(v_row->>'percent','0'),',','.')::numeric;exception when others then raise exception 'Percentual inválido.';end;if v_pct<=0 then raise exception 'Percentuais devem ser maiores que zero.';end if;if not exists(select 1 from public.z19p_profiles p where p.id=v_uid and p.account_owner_id=v_owner and p.active=true)then raise exception 'Participante inválido ou inativo.';end if;begin insert into pg_temp.z19p_split_input(user_id,pct)values(v_uid,v_pct);exception when unique_violation then raise exception 'O mesmo usuário não pode aparecer duas vezes.';end;v_sum:=v_sum+v_pct;v_count:=v_count+1;end loop;if abs(v_sum-100)>0.01 then raise exception 'A divisão precisa somar 100%%.';end if;delete from public.z19p_commission_shares where commission_id=v_comm.id and owner_id=v_owner;for v_uid,v_pct in select user_id,pct from pg_temp.z19p_split_input order by user_id loop v_i:=v_i+1;if v_i=v_count then v_amount:=round(v_comm.commission_amount-v_assigned,2);else v_amount:=round(v_comm.commission_amount*v_pct/100,2);v_assigned:=v_assigned+v_amount;end if;insert into public.z19p_commission_shares(owner_id,commission_id,recipient_user_id,share_percent,share_amount)values(v_owner,v_comm.id,v_uid,v_pct,v_amount);end loop;return jsonb_build_object('ok',true,'split',true,'commission_id',v_comm.id,'participants',v_count,'total_percent',v_sum);end$$;
grant execute on function public.z19p_set_commission_split(uuid,jsonb) to authenticated;
create or replace function public.z19p_get_my_commission_summary() returns jsonb language sql stable security definer set search_path=public as $$with me as(select auth.uid() uid,public.z19p_current_account_owner() owner_id),cfg as(select c.* from public.z19p_commission_config c join me on me.owner_id=c.owner_id limit 1),amounts as(select c.id,c.status,case when exists(select 1 from public.z19p_commission_shares sx where sx.commission_id=c.id)then coalesce((select s.share_amount from public.z19p_commission_shares s,me where s.commission_id=c.id and s.recipient_user_id=me.uid limit 1),0)when c.seller_user_id=(select uid from me)then c.commission_amount else 0 end amount from public.z19p_commissions c,me where c.owner_id=me.owner_id and c.status in('pending','approved','paid'))select jsonb_build_object('enabled',coalesce((select enabled from cfg),false),'payment_weekday',(select payment_weekday from cfg),'pending',coalesce((select sum(amount)from amounts where status='pending'),0),'approved',coalesce((select sum(amount)from amounts where status='approved'),0),'paid',coalesce((select sum(amount)from amounts where status='paid'),0));$$;
grant execute on function public.z19p_get_my_commission_summary() to authenticated;
commit;
