begin;
-- Keep every existing image/video type and existing size limit. Only enable the
-- PDF MIME already generated by the quote document workflow.
update storage.buckets
set allowed_mime_types=array_append(allowed_mime_types,'application/pdf')
where id='z19p-assets' and allowed_mime_types is not null
  and not ('application/pdf'=any(allowed_mime_types));
commit;
